---
- name: profile bash_profile
  stat: 
    path="{{ user_home.stdout }}/.bash_profile"
  register: bprof
  become: true
  

- name: Adding the path in the Profile(.bash_profile) files
  lineinfile: 
    dest: "{{ user_home.stdout }}/.bash_profile" 
    line: "{{ item.line }}"
    #state: absent
    backup: yes
#    create: yes
    insertafter: "{{ item.after }}" 
  with_items:
    - { line: "################add#####################
               \nexport TB_HOME={{ tb_home }}
               \nexport TB_SID={{ tb_sid }}
               \nexport PATH=$TB_HOME/bin:$TB_HOME/client/bin:$PATH
               \nexport LD_LIBRARY_PATH=$TB_HOME/lib:$TB_HOME/client/lib
               \n################end#####################", after: "EOF" }
  when: bprof.stat.exists == True
  become: true

- name: make profile
  stat:
    path="{{ user_home }}/.profile"
  register: prof
  become: true

- name: copy .profile
  shell: "cp {{ user_home.stdout }}/.profile {{ user_home.stdout }}/.profile.backup"
  become: true

- name: Adding the path in the Profile(.profile) files
  lineinfile:
    dest: "{{ user_home.stdout }}/.profile"
    line: "{{ item.line }}"
    #state: absent
    backup: yes
#    create: yes
    insertafter: "{{ item.after }}"
  with_items:
    - { line: "################add#####################
               \nexport TB_HOME={{ tb_home }}
               \nexport TB_SID={{ tb_sid }}
               \nexport PATH=$TB_HOME/bin:$TB_HOME/client/bin:$PATH
               \nexport LD_LIBRARY_PATH=$TB_HOME/lib:$TB_HOME/client/lib 
               \n################end#####################", after: "EOF" }
  when: prof.stat.exists == True
  become: true
