---
- name: Find my hoome
  shell: "grep '{{ ansible_user }}:' /etc/passwd | awk -F: '{ print $6 }'"
  register: user_home

- name: find java home
  stat:
    path: "{{ java_home }}"
  register: find_java

- name: make directory
  file: path={{ java_home }} state=directory
  when: find_java.stat.isdir is not defined

- name: gtar java
  unarchive:
    extra_opts="--strip-components=1"
    src=../../../files/binary/java/{{ java_version }}/jdk-8u121-linux-x64.tar.gz
    dest={{ java_home }}
  with_fileglob:
    - ../../../files/binary/java/{{ java_version }}/*
  when: find_java.stat.isdir is not defined

- name: correct java version selected
  alternatives:
    name: java
    path: "{{ java_home }}/bin/java"
    link: /usr/bin/java
  when: find_java.stat.isdir is not defined
