GRANT SELECT ON AUTH.SM_ISSUER TO USERMGT;
GRANT SELECT ON AUTH.SM_OBJECT TO USERMGT;
GRANT SELECT ON AUTH.SM_PERMISSION TO USERMGT;
GRANT SELECT ON AUTH.SM_ROLE TO USERMGT;
GRANT SELECT ON AUTH.SM_ROLE_HIERARCHY TO USERMGT;
GRANT SELECT ON AUTH.SM_ROLE_PERMISSION TO USERMGT;
GRANT SELECT ON AUTH.SM_SET TO USERMGT;
GRANT SELECT ON AUTH.SM_USER TO USERMGT;
GRANT SELECT ON AUTH.SM_USER_ROLE TO USERMGT;

commit;
exit
