CREATE TABLE AUTH.SM_ISSUER (
	IS_NAME VARCHAR(31),
	IS_TYPE VARCHAR(31),
	IS_SECRET VARCHAR(31),
	IS_ID_ENC NUMBER,
	IS_RBAC_M NUMBER
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


GRANT SELECT ON AUTH.SM_ISSUER TO PORTAL;

CREATE TABLE AUTH.SM_OBJECT (
	OBJECT_ID VARCHAR(31) NOT NULL,
	OBJECT_NAME VARCHAR(31),
	OBJECT_TYPE VARCHAR(150),
	OBJECT_SYS_ID VARCHAR(150)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX AUTH.AUTH_CON246800809 ON AUTH.SM_OBJECT (
	OBJECT_ID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE AUTH.SM_OBJECT ADD 
PRIMARY KEY (
	OBJECT_ID
);


GRANT SELECT ON AUTH.SM_OBJECT TO PORTAL;

CREATE TABLE AUTH.SM_PERMISSION (
	ID VARCHAR(31) NOT NULL,
	OBJECT_TYPE VARCHAR(1023),
	OBJECT_ID VARCHAR(31),
	ACTION VARCHAR(31),
	OBJECT_SYS_ID VARCHAR(150),
	OBJECT_NAME VARCHAR(31)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX AUTH.AUTH_CON246700918 ON AUTH.SM_PERMISSION (
	ID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE AUTH.SM_PERMISSION ADD 
PRIMARY KEY (
	ID
);


GRANT SELECT ON AUTH.SM_PERMISSION TO PORTAL;

CREATE TABLE AUTH.SM_ROLE (
	ROLE_ID VARCHAR(31) NOT NULL,
	DESCRIPTION VARCHAR(1023),
	ROLE_NAME VARCHAR(121),
	CARDINALITY NUMBER,
	PRE_ROLE_ID VARCHAR(31),
	SET_ID VARCHAR(31)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX AUTH.AUTH_CON246600847 ON AUTH.SM_ROLE (
	ROLE_ID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE AUTH.SM_ROLE ADD 
PRIMARY KEY (
	ROLE_ID
);


GRANT SELECT ON AUTH.SM_ROLE TO PORTAL;

CREATE TABLE AUTH.SM_ROLE_PERMISSION (
	ROLE_ID VARCHAR(31),
	PERMISSION_ID VARCHAR(330)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


GRANT SELECT ON AUTH.SM_ROLE_PERMISSION TO PORTAL;

CREATE TABLE AUTH.SM_USER (
	USER_ID VARCHAR(31) NOT NULL,
	PASSWD VARCHAR(31)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX AUTH.AUTH_CON246400816 ON AUTH.SM_USER (
	USER_ID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE AUTH.SM_USER ADD 
PRIMARY KEY (
	USER_ID
);


GRANT SELECT ON AUTH.SM_USER TO PORTAL;

CREATE TABLE AUTH.SM_USER_ROLE (
	USER_ID VARCHAR(31),
	ROLE_ID VARCHAR(330)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;


GRANT SELECT ON AUTH.SM_USER_ROLE TO PORTAL;

commit;
exit
