CREATE SEQUENCE "CDS"."DESKTOP_GROUP_SEQ"
START WITH 16
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE 
NOCACHE 
NOORDER;

CREATE SEQUENCE "CDS"."DESKTOP_INFO_SEQ"
START WITH 429
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE 
CACHE 20
NOORDER;

CREATE SEQUENCE "CDS"."DESKTOP_OWNER_SEQ"
START WITH 341
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE 
CACHE 20
NOORDER;

CREATE SEQUENCE "CDS"."GROUP_INFO_SEQ"
START WITH 66
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE 
CACHE 20
NOORDER;

CREATE SEQUENCE "CDS"."GROUP_USER_INFO_SEQ"
START WITH 7
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE 
NOCACHE 
NOORDER;

CREATE SEQUENCE "CDS"."IMAGE_OWNER_SEQ"
START WITH 61
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE 
CACHE 20
NOORDER;

CREATE SEQUENCE "CDS"."MONITORING_INFO_SEQ"
START WITH 18981
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE 
CACHE 20
NOORDER;

CREATE SEQUENCE "CDS"."ROLE_INFO_SEQ"
START WITH 41
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE 
CACHE 20
NOORDER;

CREATE SEQUENCE "CDS"."RX_SESSION_INFO_SEQ"
START WITH 769
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE 
CACHE 20
NOORDER;

CREATE SEQUENCE "CDS"."SESSION_LOG_SEQ"
START WITH 64
MINVALUE 1
MAXVALUE 9999999999
NOCYCLE 
NOCACHE 
NOORDER;

CREATE SEQUENCE "CDS"."SPEC_INFO_SEQ"
START WITH 163
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE 
CACHE 20
NOORDER;

CREATE SEQUENCE "CDS"."USER_DATA_OWNER_SEQ"
START WITH 21
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE 
CACHE 20
NOORDER;

CREATE SEQUENCE "CDS"."USER_INFO_SEQ"
START WITH 386
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE 
CACHE 20
NOORDER;

CREATE TABLE "CDS"."DESKTOP_GROUP_INFO" (
	"DG_IDX" NUMBER,
	"DESKTOP_IDX" NUMBER,
	"GROUP_IDX" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CDS"."DESKTOP_INFO" (
	"DESKTOP_IDX" NUMBER,
	"USER_DATA_ID" VARCHAR(45),
	"IMAGE_ID" VARCHAR(45),
	"SPEC_IDX" NUMBER,
	"USER_DATA_NAME" VARCHAR(45),
	"CONTAINER_ID" VARCHAR(45),
	"DESKTOP_STATUS" NUMBER,
	"CREATION_DATE" VARCHAR(45),
	"LAST_SESSION_TIME" VARCHAR(45),
	"CURRENT_TX_IP" VARCHAR(45),
	"DESCRIPTION" VARCHAR(45)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CDS"."DESKTOP_OWNER" (
	"DO_IDX" NUMBER,
	"USER_IDX" NUMBER,
	"DESKTOP_IDX" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CDS"."GROUP_INFO" (
	"GROUP_IDX" NUMBER,
	"GROUP_NAME" VARCHAR(45),
	"CREATION_DATE" VARCHAR(45)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CDS"."GROUP_USER_INFO" (
	"DO_IDX" NUMBER,
	"GROUP_IDX" NUMBER,
	"USER_IDX" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CDS"."IMAGE_INFO" (
	"IMAGE_ID" VARCHAR(45),
	"IMAGE_NAME" VARCHAR(45),
	"IMAGE_TAG" VARCHAR(45),
	"IMAGE_TYPE" VARCHAR(45),
	"SHARED" VARCHAR(45),
	"SUPPORT_OS" VARCHAR(45),
	"OS_VERSION" NUMBER,
	"DESCRIPTION" VARCHAR(45),
	"CREATION_DATE" VARCHAR(45)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CDS"."IMAGE_OWNER" (
	"MAPPING_IDX" NUMBER(10),
	"USER_IDX" NUMBER(10),
	"IMAGE_ID" VARCHAR(45)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CDS"."MONITORING_INFO" (
	"MONITORING_IDX" NUMBER,
	"DESKTOP_IDX" NUMBER,
	"MEMORY_USAGE" NUMBER,
	"NETWORK_IN" NUMBER,
	"NETWORK_OUT" NUMBER,
	"DISK_USAGE" NUMBER,
	"UPDATE_DATE" NUMBER,
	"CPU_TEMP" NUMBER,
	"GPU_TEMP" NUMBER,
	"NETWORK_USED_TX" NUMBER,
	"NETWORK_USED_RX" NUMBER,
	"CPU_USAGE" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CDS"."ROLE_INFO" (
	"ROLE_IDX" NUMBER,
	"ROLE_NAME" VARCHAR(45),
	"ROLE_AUTH" NUMBER
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CDS"."RX_SESSION_INFO" (
	"RX_SESSION_IDX" NUMBER(10),
	"USER_IDX" NUMBER(10),
	"IMAGE_ID" VARCHAR(45),
	"DESKTOP_IDX" NUMBER,
	"STATUS" NUMBER(10)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CDS"."SESSION_LOG" (
	"SESSION_LOG_IDX" NUMBER(10),
	"USER_DATA_NAME" VARCHAR(45),
	"START_SESSION_TIME" VARCHAR(45),
	"LAST_SESSION_TIME" VARCHAR(45),
	"RUNNING_TIME" VARCHAR(45),
	"NAME" VARCHAR(45),
	"LOCATION" VARCHAR(45)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CDS"."SPEC_INFO" (
	"SPEC_IDX" NUMBER,
	"NAME" VARCHAR(45),
	"SPECCPU" NUMBER,
	"SPECMEMORY" NUMBER,
	"QUOTASIZE" NUMBER,
	"DESCRIPTION" VARCHAR(45),
	"CREATION_DATE" VARCHAR(45)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE TABLE "CDS"."USER_INFO" (
	"USER_IDX" NUMBER(10),
	"NAME" VARCHAR(45),
	"PHONE" VARCHAR(45),
	"ID" VARCHAR(45),
	"PW" VARCHAR(45),
	"AUTH" VARCHAR(45),
	"DESCRIPTION" VARCHAR(45),
	"CREATION_DATE" VARCHAR(45),
	"GROUP_IDX" NUMBER,
	"ROLE_IDX" NUMBER,
	"DEPARTMENT" VARCHAR(45),
	"COMPANY" VARCHAR(45),
	"POSITION" VARCHAR(45)
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX "CDS"."CDS_CON58600676" ON "CDS"."USER_INFO" (
	"USER_IDX" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CDS"."CDS_CON58700775" ON "CDS"."USER_INFO" (
	"ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CDS"."CDS_CON58800102" ON "CDS"."IMAGE_INFO" (
	"IMAGE_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CDS"."CDS_CON58900061" ON "CDS"."IMAGE_OWNER" (
	"MAPPING_IDX" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CDS"."CDS_CON59400505" ON "CDS"."RX_SESSION_INFO" (
	"RX_SESSION_IDX" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CDS"."CDS_CON60100392" ON "CDS"."SPEC_INFO" (
	"SPEC_IDX" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CDS"."CDS_CON60200810" ON "CDS"."DESKTOP_INFO" (
	"DESKTOP_IDX" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CDS"."CDS_CON60900809" ON "CDS"."DESKTOP_OWNER" (
	"DO_IDX" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CDS"."CDS_CON61600674" ON "CDS"."MONITORING_INFO" (
	"MONITORING_IDX" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CDS"."CDS_CON62000362" ON "CDS"."ROLE_INFO" (
	"ROLE_IDX" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CDS"."CDS_CON62200566" ON "CDS"."GROUP_INFO" (
	"GROUP_IDX" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CDS"."CDS_CON62500544" ON "CDS"."ROLE_INFO" (
	"ROLE_NAME" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CDS"."CDS_CON62900025" ON "CDS"."GROUP_INFO" (
	"GROUP_NAME" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CDS"."CDS_CON63000464" ON "CDS"."DESKTOP_GROUP_INFO" (
	"DG_IDX" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CDS"."PK_GROUP_USER_INFO" ON "CDS"."GROUP_USER_INFO" (
	"DO_IDX" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "CDS"."PK_SESSION_LOG" ON "CDS"."SESSION_LOG" (
	"SESSION_LOG_IDX" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

ALTER TABLE "CDS"."USER_INFO" ADD 
PRIMARY KEY (
	"USER_IDX"
);

ALTER TABLE "CDS"."USER_INFO" ADD 
UNIQUE (
	"ID"
);

ALTER TABLE "CDS"."IMAGE_INFO" ADD 
PRIMARY KEY (
	"IMAGE_ID"
);

ALTER TABLE "CDS"."IMAGE_OWNER" ADD 
PRIMARY KEY (
	"MAPPING_IDX"
);

ALTER TABLE "CDS"."RX_SESSION_INFO" ADD 
PRIMARY KEY (
	"RX_SESSION_IDX"
);

ALTER TABLE "CDS"."SPEC_INFO" ADD 
PRIMARY KEY (
	"SPEC_IDX"
);

ALTER TABLE "CDS"."DESKTOP_INFO" ADD 
PRIMARY KEY (
	"DESKTOP_IDX"
);

ALTER TABLE "CDS"."DESKTOP_OWNER" ADD 
PRIMARY KEY (
	"DO_IDX"
);

ALTER TABLE "CDS"."MONITORING_INFO" ADD 
PRIMARY KEY (
	"MONITORING_IDX"
);

ALTER TABLE "CDS"."ROLE_INFO" ADD 
PRIMARY KEY (
	"ROLE_IDX"
);

ALTER TABLE "CDS"."GROUP_INFO" ADD 
PRIMARY KEY (
	"GROUP_IDX"
);

ALTER TABLE "CDS"."ROLE_INFO" ADD 
UNIQUE (
	"ROLE_NAME"
);

ALTER TABLE "CDS"."GROUP_INFO" ADD 
UNIQUE (
	"GROUP_NAME"
);

ALTER TABLE "CDS"."DESKTOP_GROUP_INFO" ADD 
PRIMARY KEY (
	"DG_IDX"
);

ALTER TABLE "CDS"."GROUP_USER_INFO" ADD CONSTRAINT "PK_GROUP_USER_INFO"
PRIMARY KEY (
	"DO_IDX"
);

ALTER TABLE "CDS"."SESSION_LOG" ADD CONSTRAINT "PK_SESSION_LOG"
PRIMARY KEY (
	"SESSION_LOG_IDX"
);

ALTER TABLE "CDS"."DESKTOP_GROUP_INFO" ADD CONSTRAINT "DESKTOP_GROUP_INFO_DESKTOP_IDX_FK"
FOREIGN KEY (
	"DESKTOP_IDX"
) REFERENCES "CDS"."DESKTOP_INFO" (
	"DESKTOP_IDX"
) ON DELETE CASCADE;

ALTER TABLE "CDS"."DESKTOP_GROUP_INFO" ADD CONSTRAINT "DESKTOP_GROUP_INFO_GROUP_IDX_FK"
FOREIGN KEY (
	"GROUP_IDX"
) REFERENCES "CDS"."GROUP_INFO" (
	"GROUP_IDX"
) ON DELETE CASCADE;

ALTER TABLE "CDS"."DESKTOP_OWNER" ADD CONSTRAINT "DESKTOP_INFO_DESKTOP_IDX_DO_FK"
FOREIGN KEY (
	"DESKTOP_IDX"
) REFERENCES "CDS"."DESKTOP_INFO" (
	"DESKTOP_IDX"
) ON DELETE CASCADE;

ALTER TABLE "CDS"."RX_SESSION_INFO" ADD CONSTRAINT "DESKTOP_INFO_DESKTOP_IDX_RSI_FK"
FOREIGN KEY (
	"DESKTOP_IDX"
) REFERENCES "CDS"."DESKTOP_INFO" (
	"DESKTOP_IDX"
) ON DELETE CASCADE;

ALTER TABLE "CDS"."MONITORING_INFO" ADD CONSTRAINT "DESKTOP_INFO_MONITORING_INFO_DESKTOP_IDX_FK"
FOREIGN KEY (
	"DESKTOP_IDX"
) REFERENCES "CDS"."DESKTOP_INFO" (
	"DESKTOP_IDX"
) ON DELETE CASCADE;

ALTER TABLE "CDS"."DESKTOP_INFO" ADD CONSTRAINT "IMAGE_INFO_IMAGE_ID_DI_FK"
FOREIGN KEY (
	"IMAGE_ID"
) REFERENCES "CDS"."IMAGE_INFO" (
	"IMAGE_ID"
) ON DELETE CASCADE;

ALTER TABLE "CDS"."IMAGE_OWNER" ADD CONSTRAINT "IMAGE_INFO_IMAGE_ID_DO_FK"
FOREIGN KEY (
	"IMAGE_ID"
) REFERENCES "CDS"."IMAGE_INFO" (
	"IMAGE_ID"
) ON DELETE CASCADE;

ALTER TABLE "CDS"."RX_SESSION_INFO" ADD CONSTRAINT "IMAGE_INFO_IMAGE_ID_RSI_FK"
FOREIGN KEY (
	"IMAGE_ID"
) REFERENCES "CDS"."IMAGE_INFO" (
	"IMAGE_ID"
) ON DELETE CASCADE;

ALTER TABLE "CDS"."DESKTOP_INFO" ADD CONSTRAINT "SPEC_INFO_SPEC_IDX_DI_FK"
FOREIGN KEY (
	"SPEC_IDX"
) REFERENCES "CDS"."SPEC_INFO" (
	"SPEC_IDX"
) ON DELETE CASCADE;

ALTER TABLE "CDS"."USER_INFO" ADD CONSTRAINT "USER_INFO_GROUP_INFO_GROUP_IDX"
FOREIGN KEY (
	"GROUP_IDX"
) REFERENCES "CDS"."GROUP_INFO" (
	"GROUP_IDX"
);

ALTER TABLE "CDS"."USER_INFO" ADD CONSTRAINT "USER_INFO_ROLE_INFO_ROLE_IDX"
FOREIGN KEY (
	"ROLE_IDX"
) REFERENCES "CDS"."ROLE_INFO" (
	"ROLE_IDX"
);

ALTER TABLE "CDS"."IMAGE_OWNER" ADD CONSTRAINT "USER_INFO_USER_IDX_DO_FK"
FOREIGN KEY (
	"USER_IDX"
) REFERENCES "CDS"."USER_INFO" (
	"USER_IDX"
) ON DELETE CASCADE;

ALTER TABLE "CDS"."DESKTOP_OWNER" ADD CONSTRAINT "USER_INFO_USER_IDX_DO_FK2"
FOREIGN KEY (
	"USER_IDX"
) REFERENCES "CDS"."USER_INFO" (
	"USER_IDX"
) ON DELETE CASCADE;

ALTER TABLE "CDS"."RX_SESSION_INFO" ADD CONSTRAINT "USER_INFO_USER_IDX_RSI_FK"
FOREIGN KEY (
	"USER_IDX"
) REFERENCES "CDS"."USER_INFO" (
	"USER_IDX"
) ON DELETE CASCADE;

commit;
exit
