CREATE TABLE "IMPADMIN"."AUTOSCALEEVENTINFO" (
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"AUTOSCALEID" NUMBER,
	"EVENTTYPE" NUMBER,
	"EVENTTIME" TIMESTAMP,
	"CAUSEDBY" VARCHAR(30),
	"NUMBEROFINSTANCE" NUMBER
);


CREATE TABLE "IMPADMIN"."AUTOSCALEINFO" (
	"AUTOSCALEID" NUMBER,
	"MIN" NUMBER,
	"MAX" NUMBER,
	"OUTEVENTID" NUMBER,
	"OUTPOLICY" VARCHAR(255),
	"OUTCOOLDOWN" NUMBER,
	"INEVENTID" NUMBER,
	"INPOLICY" VARCHAR(255),
	"INCOOLDOWN" NUMBER,
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"RECENTINEVENT" TIMESTAMP,
	"RECENTOUTEVENT" TIMESTAMP,
	"EVENTHANDLING" NUMBER,
	"STATUS" VARCHAR(10),
	"AUTOSCALENAME" VARCHAR(255),
	"SERVICETYPE" VARCHAR(16),
	"DESCRIPTION" VARCHAR(255)
);

CREATE TABLE "IMPADMIN"."BLOCKSTORAGEIMAGEINFO" (
	"TENANTID" NUMBER(15),
	"PROJECTID" NUMBER(15),
	"IMAGEID" NUMBER(15),
	"IMAGEUUID" VARCHAR(32),
	"IMAGENAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(1024),
	"RECOMMEND" VARCHAR(1),
	"SHARED" NUMBER,
	"STATUS" VARCHAR(5),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"SNAPUUID" VARCHAR(32),
	"SNAPID" NUMBER(15),
	"OSINSTALLED" VARCHAR(1),
	"CREATOR" VARCHAR(255),
	"UPDATER" VARCHAR(255)
);


CREATE TABLE "IMPADMIN"."BLOCKSTORAGEINFO" (
	"BLOCKSTORAGEID" NUMBER,
	"BLOCKSTORAGENAME" VARCHAR(255),
	"TOTALSIZE" NUMBER,
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"DESCRIPTION" VARCHAR(1024),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"SHARED" NUMBER,
	"CREATOR" VARCHAR(255),
	"UPDATER" VARCHAR(255),
	"ATTACHEDINSTANCEID" VARCHAR(32),
	"STATUS" VARCHAR(255),
	"METADATA" VARCHAR(255),
	"NAME" VARCHAR(255),
	"SRCIMAGENAME" VARCHAR(255),
	"BLOCKSTORAGESRCPATH" VARCHAR(255),
	"TAG" VARCHAR(255),
	"ATTACHEDINSTANCE" NUMBER,
	"MEASURE" VARCHAR(2),
	"ISROOT" NUMBER,
	"SOURCE" VARCHAR(1024)
);


CREATE TABLE "IMPADMIN"."BLOCKSTORAGEMAPPING" (
	"INSTANCEID" NUMBER,
	"BLOCKSTORAGEID" NUMBER,
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"DESCRIPTION" VARCHAR(255)
);

CREATE TABLE "IMPADMIN"."BLOCKSTORAGESNAPINFO" (
	"TENANTID" NUMBER(15),
	"PROJECTID" NUMBER(15),
	"SNAPID" NUMBER(15),
	"SNAPUUID" VARCHAR(32),
	"SNAPNAME" VARCHAR(1024),
	"BLOCKSTORAGEID" NUMBER,
	"BLOCKSTORAGEUUID" VARCHAR(32),
	"ISPROTECTED" VARCHAR(1),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"CREATOR" VARCHAR(255),
	"UPDATER" VARCHAR(255)
);


CREATE TABLE "IMPADMIN"."COMMGROUPINFO" (
	"COMMGROUPID" NUMBER,
	"COMMGROUPUUID" VARCHAR(255),
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"NAME" VARCHAR(100),
	"STATUS" VARCHAR(45) DEFAULT 'Active',
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"SECUREMODE" NUMBER(1) DEFAULT '0',
	"UPDATEDTIME" TIMESTAMP,
	"CREATOR" VARCHAR(45) DEFAULT NULL,
	"UPDATER" VARCHAR(45)
);

CREATE TABLE "IMPADMIN"."DBINFO" (
	"DBID" NUMBER,
	"STORAGESERVERGROUPID" NUMBER,
	"DBINSTANCEID" NUMBER,
	"TOTALSIZE" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"PROJECTID" NUMBER,
	"INSTALLFLAG" NUMBER,
	"STORAGETYPE" NUMBER,
	"TENANTID" NUMBER,
	"CREATOR" VARCHAR(255),
	"TAGS" VARCHAR(255),
	"UPDATER" VARCHAR(255)
);

CREATE TABLE "IMPADMIN"."DNSRECORDINFO" (
	"RECORDID" NUMBER(15),
	"RECORDUUID" VARCHAR(64),
	"ZONEID" NUMBER(15),
	"DATATYPE" VARCHAR(10),
	"TTL" NUMBER(12),
	"HOST" VARCHAR(64),
	"DATA" VARCHAR(1000),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
);


CREATE TABLE "IMPADMIN"."DNSSERVERINFO" (
	"TENANTID" NUMBER(15),
	"INSTANCEID" NUMBER(15),
	"NETWORKID" NUMBER(15),
	"TYPE" NUMBER(3),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
);


CREATE TABLE "IMPADMIN"."DNSZONEINFO" (
	"ZONEID" NUMBER(15),
	"ZONEUUID" VARCHAR(64),
	"NETWORKID" NUMBER(15),
	"DOMAINNAME" VARCHAR(256),
	"DESCRIPTION" VARCHAR(256),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
);


CREATE TABLE "IMPADMIN"."FILESTORAGEINFO" (
	"FILESTORAGEID" NUMBER,
	"STORAGEUNITID" NUMBER,
	"STORAGEGROUPID" NUMBER,
	"TOTALSIZE" NUMBER(9),
	"ISRW" NUMBER(1),
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"CDSLOGINUSERID" VARCHAR(255),
	"CDSLOGINUSERPW" VARCHAR(255),
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(1024),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"METADATA" VARCHAR(2048),
	"TAG" VARCHAR(4096),
	"SHARED" NUMBER,
	"CREATOR" VARCHAR(4096),
	"ATTACHEDCONTAINER" NUMBER,
	"MEASURE" VARCHAR(4096),
	"FREESIZE" NUMBER,
	"UPDATER" VARCHAR(4096),
	"FSKEY" VARCHAR(255),
	"STATUS" VARCHAR(255),
	"SOURCE" VARCHAR(1024)
);


CREATE TABLE "IMPADMIN"."FILESTORAGEMAPPING" (
	"INSTANCEID" NUMBER,
	"FILESTORAGEID" NUMBER,
	"INSTANCEMOUNTPATH" VARCHAR(255),
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER
);


CREATE TABLE "IMPADMIN"."HOSTHISTORY" (
	"ID" NUMBER,
	"HOSTID" NUMBER,
	"SERVICE" VARCHAR(40),
	"TYPE" VARCHAR(20),
	"CAUSE" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"DETAIL" VARCHAR(2048),
	"CURRENTTIME" TIMESTAMP
);

CREATE TABLE "IMPADMIN"."HOSTINFO" (
	"HOSTID" NUMBER,
	"HOSTNAME" VARCHAR(255),
	"HYPERVISORTYPE" VARCHAR(255),
	"CPUARCH" VARCHAR(255),
	"TOTALCPU" NUMBER,
	"TOTALMEMORY" NUMBER,
	"TOTALDISK" NUMBER,
	"ACCESSNAME" VARCHAR(255),
	"ACCESSAUTH" VARCHAR(2048),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"DESCRIPTION" VARCHAR(255),
	"ACCESSPORT" NUMBER
);

CREATE TABLE "IMPADMIN"."HOSTRESOURCEINFO" (
	"HOSTID" NUMBER,
	"STATUS" VARCHAR(255),
	"ACTIVE" NUMBER(1),
	"HOSTTYPE" VARCHAR(255),
	"NODETYPE" NUMBER,
	"VTOTALCPU" NUMBER,
	"VFREECPU" NUMBER,
	"VTOTALMEMORY" NUMBER,
	"VFREEMEMORY" NUMBER,
	"POOLEDDISK" NUMBER,
	"FREEDISK" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"DESCRIPTION" VARCHAR(255),
	"AVAILABILITYZONE" VARCHAR(255),
	"SSDPOOLEDDISK" NUMBER(10) DEFAULT 0,
	"SSDFREEDISK" NUMBER(10) DEFAULT 0,
	"FARM" VARCHAR(25),
	"CEPHSTORAGE" NUMBER,
	"VTOTALSSD" NUMBER,
	"VFREESSD" NUMBER,
	"VTOTALHDD" NUMBER,
	"VFREEHDD" NUMBER
);

CREATE TABLE "IMPADMIN"."HOSTSHAREINSTANCEMAPPINGINFO" (
	"HOSTSHAREINSTANCEMAPPINGID" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"HOSTPATH" VARCHAR(255),
	"HOSTSHAREINSTANCEMAPPINGUUID" VARCHAR(255),
	"INSTANCEID" NUMBER(19),
	"INSTANCEPATH" VARCHAR(255),
	"INSTANCEUUID" VARCHAR(255),
	"UPDATEDTIME" TIMESTAMP,
	"ZFS" NUMBER(10)
);

CREATE TABLE "IMPADMIN"."IMAGE" (
	"TENANTID" NUMBER(15),
	"TENANTUUID" VARCHAR(32),
	"PROJECTID" NUMBER(15),
	"PROJECTUUID" VARCHAR(32),
	"UPLOADERUUID" VARCHAR(32),
	"IMAGEID" NUMBER(15),
	"IMAGEUUID" VARCHAR(32),
	"IMAGENAME" VARCHAR(255),
	"IMAGETAG" VARCHAR(255),
	"IMAGETYPE" VARCHAR(255),
	"DESCRIPTION" VARCHAR(1024),
	"SHARED" VARCHAR(15),
	"STATE" VARCHAR(5),
	"UPLOADEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"UPDATERUUID" VARCHAR(32),
	"UPLOADERID" NUMBER(15),
	"UPDATERID" NUMBER(15),
	"PRODUCTNAME" VARCHAR(1024),
	"PRODUCTVERSION" VARCHAR(1024),
	"ISSNAPSHOT" VARCHAR(2),
	"IMAGEFROM" VARCHAR(32),
	"TENANTNAME" VARCHAR(1024),
	"PROJECTNAME" VARCHAR(1024),
	"UPLOADERNAME" VARCHAR(1024),
	"UPDATERNAME" VARCHAR(1024),
	"DEFAULTCHECK" VARCHAR(2)
);

CREATE TABLE "IMPADMIN"."IMAGELAYERMAPPED" (
	"IMAGEID" NUMBER(15),
	"LAYERID" VARCHAR(64),
	"LAYERORDER" NUMBER(15)
);

CREATE TABLE "IMPADMIN"."IMAGEMANIFEST" (
	"IMAGENAME" VARCHAR(255),
	"IMAGEVERSION" VARCHAR(255),
	"IMAGETYPE" VARCHAR(255),
	"SUPPORTOS" VARCHAR(255),
	"IMAGECLASSIFICATION" VARCHAR(255),
	"IMAGEURL" VARCHAR(255),
	"SHA256" VARCHAR(255)
);

CREATE TABLE "IMPADMIN"."IMAGESTATEINFO" (
	"IMAGEID" NUMBER(15),
	"TENANTID" NUMBER(15),
	"STATEFLAG" NUMBER(2)
);

CREATE TABLE "IMPADMIN"."INNERFILESYSTEMINFO" (
	"INNERFILESYSTEMID" NUMBER,
	"STORAGEUNITID" NUMBER,
	"ROOTPATHNAME" VARCHAR(255),
	"TOTALSIZE" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255)
);

CREATE TABLE "IMPADMIN"."INSTANCECOMMGROUPINFO" (
	"INSTANCEID" NUMBER,
	"COMMGROUPID" NUMBER
);

CREATE TABLE "IMPADMIN"."INSTANCEINFO" (
	"INSTANCEID" NUMBER,
	"INSTANCEUUID" VARCHAR(255),
	"TENANTID" NUMBER,
	"TENANTUUID" VARCHAR(255),
	"PROJECTID" NUMBER,
	"PROJECTUUID" VARCHAR(255),
	"CREATOR" VARCHAR(255),
	"INSTANCENAME" VARCHAR(255),
	"INSTANCEDESCRIPTION" VARCHAR(255),
	"INSTANCETAGS" VARCHAR(255),
	"INSTANCETYPE" VARCHAR(255),
	"IMAGEID" NUMBER,
	"IMAGEUUID" VARCHAR(255),
	"RESULT" VARCHAR(255),
	"RESULTMESSAGE" VARCHAR(600),
	"HYPERVISORTYPE" VARCHAR(255),
	"SPECID" NUMBER,
	"SPECUUID" VARCHAR(255),
	"CPUS" NUMBER,
	"MEMORY" NUMBER,
	"INSTANCESTATUS" VARCHAR(255),
	"ENV" VARCHAR(4095),
	"METADATA" VARCHAR(4095),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"AUTOSCALEID" NUMBER,
	"AUTOSCALEUUID" VARCHAR(255),
	"STORAGEGROUPID" NUMBER,
	"STORAGEGROUPUUID" VARCHAR(255),
	"STORAGETYPE" NUMBER,
	"INSTANCEGROUPID" NUMBER,
	"INSTANCEGROUPUUID" VARCHAR(255),
	"BACKENDIP" VARCHAR(255),
	"FRONTENDIP" VARCHAR(255),
	"PUBLICIPID" NUMBER,
	"PUBLICIPUUID" VARCHAR(255),
	"ISCDS" NUMBER,
	"AUTOCOUNT" NUMBER,
	"ISDB" NUMBER,
	"ISSERVER" NUMBER,
	"ISSYSTEM" NUMBER,
	"ACTIONID" NUMBER,
	"HOSTID" NUMBER,
	"INSTANCEPMAC" VARCHAR(255),
	"ISLB" NUMBER,
	"EVENTSTATUS" VARCHAR(255),
	"DBID" NUMBER,
	"DBMETADATA" VARCHAR(4096),
	"USBCOPYENABLE" NUMBER,
	"RECOVERYONHOSTFAILURE" NUMBER,
	"RESTARTONINSTANCEFAILURE" NUMBER,
	"INSTANCEFAILURECOUNT" NUMBER,
	"FAILURESTATUS" NUMBER,
	"WAITINGSTATUSCHANGE" NUMBER,
	"SECURITYLEVEL" NUMBER,
	"UPDATER" VARCHAR(255)
);

CREATE TABLE "IMPADMIN"."INSTANCESPECINFO" (
	"SPECID" NUMBER(15),
	"SPECUUID" VARCHAR(25),
	"SPECTYPE" VARCHAR(255),
	"SPECCPU" NUMBER(2),
	"SPECMEMORY" NUMBER(10)
);

CREATE TABLE "IMPADMIN"."INSTANCETEMPLATEINFO" (
	"INSTANCETEMPLATEID" NUMBER,
	"TYPE" NUMBER,
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"NAME" VARCHAR(255),
	"IMAGEUUID" VARCHAR(255),
	"SPECUUID" VARCHAR(255),
	"CREATOR" VARCHAR(255),
	"UPDATER" VARCHAR(255),
	"DATA" BLOB
);


CREATE TABLE "IMPADMIN"."KEYPAIR" (
	"KEYPAIRID" NUMBER,
	"KEYPAIRUUID" VARCHAR(8),
	"TENANTUUID" VARCHAR(8),
	"PROJECTUUID" VARCHAR(8),
	"KEYPAIRNAME" VARCHAR(80),
	"PUBLICKEY" VARCHAR(4096),
	"PRIVATEKEY" VARCHAR(4096),
	"FINGERPRINT" VARCHAR(4096),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
);


CREATE TABLE "IMPADMIN"."KEYPAIRMAPPING" (
	"INSTANCEID" NUMBER,
	"KEYPAIRID" NUMBER,
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER
);


CREATE TABLE "IMPADMIN"."LAYER" (
	"LAYERID" VARCHAR(64),
	"REFCNT" NUMBER(15)
);



CREATE TABLE "IMPADMIN"."METERING" (
	"TENANTID" NUMBER,
	"TENANTUUID" VARCHAR(10),
	"PROJECTID" NUMBER,
	"PROJECTUUID" VARCHAR(10),
	"METERINGTYPE" VARCHAR(15),
	"VOLUMETYPE" VARCHAR(15),
	"VOLUME" NUMBER,
	"USAGETIME" NUMBER,
	"METERINGDATE" TIMESTAMP,
	"MILLISECOND" NUMBER
);


CREATE TABLE "IMPADMIN"."NETWORKINFO" (
	"NETWORKID" NUMBER,
	"VLANID" NUMBER(5),
	"TENANTID" NUMBER,
	"NETWORKUUID" VARCHAR(255),
	"NAME" VARCHAR(40),
	"TYPE" NUMBER(1),
	"CREATEDTIME" TIMESTAMP,
	"STATUS" VARCHAR(20) DEFAULT 'Active',
	"CREATOR" VARCHAR(20)
);


CREATE TABLE "IMPADMIN"."NODEIMAGE" (
	"NODEIP" VARCHAR(15),
	"IMAGEID" NUMBER(15),
	"REFCNT" NUMBER(15)
);

CREATE TABLE "IMPADMIN"."OBJSTORAGEGATEWAYINFO" (
	"HOSTID" NUMBER,
	"RGWPORT" NUMBER
);


CREATE TABLE "IMPADMIN"."OBJSTORAGEINFO" (
	"OSID" NUMBER,
	"OSCREATETIME" TIMESTAMP,
	"OSACCESSKEY" VARCHAR(255),
	"OSSECRETKEY" VARCHAR(255),
	"OSSIZEMB" NUMBER,
	"OSNAME" VARCHAR(255),
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"OSUPDATEDTIME" TIMESTAMP
);

CREATE TABLE "IMPADMIN"."PHYSICALIMAGE" (
	"IMAGEID" NUMBER(15),
	"IMAGEUUID" VARCHAR(32),
	"PRODUCTNAME" VARCHAR(255),
	"PRODUCTVERSION" VARCHAR(255),
	"IMAGECMD" VARCHAR(1024),
	"IMAGEENV" VARCHAR(4096),
	"IMAGEFROM" VARCHAR(255),
	"SUPPORTOS" VARCHAR(255),
	"DEFAULTCHECK" VARCHAR(2),
	"INSTALLEDPROGRAMS" VARCHAR(4096),
	"ISSNAPSHOT" VARCHAR(2),
	"IMPORTEDTIME" TIMESTAMP,
	"EDITEDTIME" TIMESTAMP,
	"IMAGECLASSIFICATION" VARCHAR(1024),
	"WORKINGDIRECTORY" VARCHAR(4096)
);

CREATE TABLE "IMPADMIN"."PPORTINFO" (
	"PPORTID" NUMBER,
	"NAME" VARCHAR(255),
	"HOSTID" NUMBER,
	"NETWORKTYPE" VARCHAR(255),
	"VLANID" VARCHAR(255),
	"IPADDR" VARCHAR(255),
	"MACADDR" VARCHAR(255),
	"PMACADDR" VARCHAR(255),
	"PORT" VARCHAR(255),
	"AGGREGATEDPORT" VARCHAR(255),
	"SWITCHDPID" NUMBER,
	"SWITCHPORT" NUMBER,
	"SWITCHNAME" VARCHAR(255),
	"ISACTIVE" NUMBER,
	"ISAGGREGATED" NUMBER,
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"SUBNETUUID" VARCHAR(10),
	"IPVALUE" NUMBER
);

CREATE TABLE "IMPADMIN"."PUBLICIPINFO" (
	"PUBLICIP" VARCHAR(20),
	"PUBLICIPID" NUMBER,
	"PUBLICIPUUID" VARCHAR(255),
	"VPORTID" NUMBER,
	"CREATEDTIME" TIMESTAMP,
	"STATUS" VARCHAR(45) DEFAULT 'Active'
);

CREATE TABLE "IMPADMIN"."STORAGEGROUPINFO" (
	"STORAGEGROUPID" NUMBER,
	"TOTALSIZE" NUMBER,
	"TOTALSTORAGENUMBER" NUMBER,
	"USAGE" VARCHAR(255),
	"STORAGETYPE" NUMBER,
	"FREESIZE" NUMBER,
	"TENANTID" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
);


CREATE TABLE "IMPADMIN"."STORAGESERVERGROUPINFO" (
	"STORAGESERVERGROUPID" NUMBER,
	"STORAGEGROUPID" NUMBER,
	"TENANTID" NUMBER,
	"SSVRTYPE" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"PRIVATEPATHNAME" VARCHAR(255)
);


CREATE TABLE "IMPADMIN"."STORAGESERVERINFO" (
	"STORAGESERVERID" NUMBER,
	"STORAGEUNITID" NUMBER,
	"STORAGESERVERGROUPID" NUMBER,
	"STORAGESERVERIP" VARCHAR(255),
	"STORAGESERVERPORT" NUMBER,
	"INSTANCEID" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
);


CREATE TABLE "IMPADMIN"."STORAGEUNITINFO" (
	"STORAGEUNITID" NUMBER,
	"STORAGENODEID" NUMBER,
	"STORAGEGROUPID" NUMBER,
	"TOTALSIZE" NUMBER,
	"NAME" VARCHAR(255),
	"DESCRIPTION" VARCHAR(255),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"STORAGETYPE" NUMBER
);


CREATE TABLE "IMPADMIN"."SUBNETINFO" (
	"SUBNETID" NUMBER,
	"NETWORKID" NUMBER,
	"SUBNETUUID" VARCHAR(255),
	"IPADDR" VARCHAR(255),
	"NETMASK" VARCHAR(45),
	"CIDR" NUMBER(3),
	"GATEWAY" VARCHAR(45),
	"DNS" VARCHAR(45),
	"VLANID" NUMBER(5),
	"NAME" VARCHAR(40),
	"TYPE" NUMBER(1),
	"ISLB" NUMBER(1),
	"CREATEDTIME" TIMESTAMP,
	"STATUS" VARCHAR(20) DEFAULT 'Active',
	"ISHOST" NUMBER(1),
	"CREATOR" VARCHAR(20),
	"IPMAP" BLOB
);


CREATE TABLE "IMPADMIN"."TARGETINSTANCE" (
	"INSTANCEID" NUMBER,
	"INSTANCEUUID" VARCHAR(200),
	"TARGETPOOLID" NUMBER,
	"DSCP" NUMBER,
	"WEIGHT" NUMBER,
	"STATUS" VARCHAR(200) DEFAULT NULL,
	"DESCRIPTION" VARCHAR(200),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP
);

CREATE TABLE "IMPADMIN"."TARGETPOOL" (
	"TARGETPOOLID" NUMBER,
	"TARGETPOOLUUID" VARCHAR(200),
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"RULEID" NUMBER,
	"TARGETPOOLNAME" VARCHAR(200),
	"TARGETPOOLPORT" NUMBER,
	"PORTFORWARDING" NUMBER,
	"TARGETPORT" NUMBER,
	"VIP" VARCHAR(200),
	"HEALTHCHECK" NUMBER,
	"DESCRIPTION" VARCHAR(200),
	"TAG" VARCHAR(200),
	"CREATOR" VARCHAR(200),
	"CREATEDTIME" TIMESTAMP,
	"UPDATEDTIME" TIMESTAMP,
	"UPDATER" VARCHAR(200)
);

CREATE TABLE "IMPADMIN"."TENANTSTORAGE" (
	"STORAGEID" NUMBER,
	"STORAGEUUID" VARCHAR(10),
	"TENANTID" NUMBER,
	"TENANTUUID" VARCHAR(10),
	"STORAGESIZE" NUMBER,
	"FREESIZE" NUMBER,
	"CREATETIME" TIMESTAMP,
	"UPDATETIME" TIMESTAMP
);


CREATE TABLE "IMPADMIN"."USERHISTORYINFO" (
	"HISTORYID" NUMBER,
	"USERID" VARCHAR(255),
	"TENANTID" NUMBER,
	"PROJECTID" NUMBER,
	"INSTANCEID" NUMBER,
	"SRCTYPE" VARCHAR(255),
	"STATUS" VARCHAR(255),
	"EVENTTYPE" NUMBER,
	"DETAIL" VARCHAR(255),
	"UPDATEDINFO" VARCHAR(255),
	"MESSAGE" VARCHAR(255),
	"CURRENTTIME" TIMESTAMP,
	"INSTANCENAME" VARCHAR(255),
	"SPECID" NUMBER,
	"IMAGEID" NUMBER
);


CREATE TABLE "IMPADMIN"."VMIMAGE" (
	"TENANTID" NUMBER(15),
	"TENANTUUID" VARCHAR(32),
	"TENANTNAME" VARCHAR(1024),
	"PROJECTID" NUMBER(15),
	"PROJECTUUID" VARCHAR(32),
	"PROJECTNAME" VARCHAR(1024),
	"IMAGEID" NUMBER(15),
	"IMAGEUUID" VARCHAR(32),
	"IMAGENAME" VARCHAR(1024),
	"IMAGETAG" VARCHAR(255),
	"IMAGETYPE" VARCHAR(255),
	"IMAGECLASSIFICATION" VARCHAR(255),
	"IMAGEHASH" VARCHAR(255),
	"CLOUDINIT" VARCHAR(1024),
	"DESCRIPTION" VARCHAR(1024),
	"BACKINGCHAIN" VARCHAR(1024),
	"PRODUCTNAME" VARCHAR(1024),
	"PRODUCTVERSION" VARCHAR(1024),
	"SUPPORTOS" VARCHAR(32),
	"DEFAULTCHECK" VARCHAR(32),
	"SHARED" VARCHAR(32),
	"STATE" VARCHAR(32),
	"UPLOADEDTIME" TIMESTAMP,
	"UPLOADERID" NUMBER(15),
	"UPLOADERUUID" VARCHAR(32),
	"UPLOADERNAME" VARCHAR(1024),
	"UPDATEDTIME" TIMESTAMP,
	"UPDATERID" NUMBER(15),
	"UPDATERUUID" VARCHAR(32),
	"UPDATERNAME" VARCHAR(1024),
	"ISBLK" NUMBER(1)
);


CREATE TABLE "IMPADMIN"."VPORTINFO" (
	"VPORTID" NUMBER,
	"MAC1" VARCHAR(45),
	"MAC2" NUMBER(5),
	"VLANID" NUMBER(5),
	"NETWORKID" NUMBER,
	"IPADDR" VARCHAR(30),
	"MACADDR" VARCHAR(30),
	"SUBNETID" NUMBER,
	"VPORTUUID" VARCHAR(255),
	"NAME" VARCHAR(40),
	"STATUS" VARCHAR(45) DEFAULT 'Active',
	"NETWORKTYPE" VARCHAR(50),
	"INSTANCEID" NUMBER DEFAULT -1,
	"TARGETPOOLID" NUMBER DEFAULT -1,
	"CREATEDTIME" TIMESTAMP,
	"ISSTATIC" NUMBER DEFAULT 0,
	"STATICGROUPID" NUMBER,
	"CREATOR" VARCHAR(20),
	"UPDATEDTIME" TIMESTAMP,
	"UPDATOR" VARCHAR(20),
	"PROJECTID" NUMBER,
	"TENANTID" NUMBER,
	"TENANTNAME" VARCHAR(20)
);


CREATE TABLE "IMPADMIN"."VSWITCHINFO" (
	"VLANID" NUMBER(5),
	"HOSTID" NUMBER,
	"NAME" VARCHAR(100),
	"PORTNAME" VARCHAR(100)
);


CREATE TABLE "IMPADMIN"."WEBCONSOLEINFO" (
	"INSTANCEID" NUMBER(12),
	"SOCATPID" NUMBER(12),
	"WEBSOCKETPID" NUMBER(12),
	"SOCATPORT" NUMBER(12),
	"WEBSOCKETPORT" NUMBER(12),
	"CREATETIME" TIMESTAMP,
	"ACCESSTIME" TIMESTAMP,
	"HOSTID" NUMBER
);


CREATE TABLE "IMPADMIN"."WEB_CONSOLE" (
	"INSTANCE_ID" NUMBER,
	"HOST_ID" NUMBER,
	"WEBSOCK_PORT" NUMBER,
	"SOCAT_PORT" NUMBER,
	"CREATE_DATE" TIMESTAMP,
	"LAST_ACCESS_DATE" TIMESTAMP
);

CREATE UNIQUE INDEX "IMPADMIN"."HOST_PRIM" ON "IMPADMIN"."HOSTINFO" (
	"HOSTID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMAGELAYERMAPPED_COMPLEX_PK" ON "IMPADMIN"."IMAGELAYERMAPPED" (
	"IMAGEID" ASC,
	"LAYERID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "IMPADMIN"."IMAGEMANIFEST_PK" ON "IMPADMIN"."IMAGEMANIFEST" (
	"IMAGENAME" ASC,
	"IMAGEVERSION" ASC,
	"IMAGECLASSIFICATION" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMAGE_COMPLEX_PK" ON "IMPADMIN"."IMAGE" (
	"TENANTID" ASC,
	"PROJECTID" ASC,
	"IMAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON100200831" ON "IMPADMIN"."VSWITCHINFO" (
	"VLANID" ASC,
	"HOSTID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON100700860" ON "IMPADMIN"."INSTANCECOMMGROUPINFO" (
	"INSTANCEID" ASC,
	"COMMGROUPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON100900523" ON "IMPADMIN"."VMIMAGE" (
	"IMAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON132600335" ON "IMPADMIN"."BLOCKSTORAGEINFO" (
	"BLOCKSTORAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON141600995" ON "IMPADMIN"."BLOCKSTORAGEMAPPING" (
	"BLOCKSTORAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON175700688" ON "IMPADMIN"."BLOCKSTORAGEIMAGEINFO" (
	"IMAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON179300794" ON "IMPADMIN"."HOSTHISTORY" (
	"ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON179900184" ON "IMPADMIN"."PPORTINFO" (
	"PPORTID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON268500460" ON "IMPADMIN"."TARGETPOOL" (
	"TARGETPOOLID" ASC,
	"TENANTID" ASC,
	"PROJECTID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON269500268" ON "IMPADMIN"."TARGETINSTANCE" (
	"INSTANCEID" ASC,
	"TARGETPOOLID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON280500661" ON "IMPADMIN"."AUTOSCALEINFO" (
	"AUTOSCALEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON77100123" ON "IMPADMIN"."FILESTORAGEINFO" (
	"FILESTORAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON92200033" ON "IMPADMIN"."LAYER" (
	"LAYERID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON94100472" ON "IMPADMIN"."NETWORKINFO" (
	"NETWORKID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON94200868" ON "IMPADMIN"."NETWORKINFO" (
	"NETWORKUUID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON95400368" ON "IMPADMIN"."SUBNETINFO" (
	"SUBNETID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON95500850" ON "IMPADMIN"."SUBNETINFO" (
	"SUBNETUUID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON96500735" ON "IMPADMIN"."COMMGROUPINFO" (
	"COMMGROUPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON96600707" ON "IMPADMIN"."COMMGROUPINFO" (
	"COMMGROUPUUID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON96900636" ON "IMPADMIN"."INSTANCEINFO" (
	"INSTANCEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON98200899" ON "IMPADMIN"."VPORTINFO" (
	"VPORTID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON98300172" ON "IMPADMIN"."VPORTINFO" (
	"VPORTUUID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON99200547" ON "IMPADMIN"."PUBLICIPINFO" (
	"PUBLICIPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."IMPADMIN_CON99300211" ON "IMPADMIN"."PUBLICIPINFO" (
	"PUBLICIPUUID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."METERINGUNIQUE" ON "IMPADMIN"."METERING" (
	"TENANTID" ASC,
	"PROJECTID" ASC,
	"METERINGTYPE" ASC,
	"VOLUMETYPE" ASC,
	"METERINGDATE" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."NODEIMAGE_COMPLEX_PK" ON "IMPADMIN"."NODEIMAGE" (
	"NODEIP" ASC,
	"IMAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;



CREATE UNIQUE INDEX "IMPADMIN"."PK_BLOCKSTORAGESNAPINFO" ON "IMPADMIN"."BLOCKSTORAGESNAPINFO" (
	"SNAPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_DBINFO" ON "IMPADMIN"."DBINFO" (
	"DBID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_FILESTORAGEMAPPING" ON "IMPADMIN"."FILESTORAGEMAPPING" (
	"INSTANCEID" ASC,
	"FILESTORAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_INNERFILESYSTEMINFO" ON "IMPADMIN"."INNERFILESYSTEMINFO" (
	"INNERFILESYSTEMID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "IMPADMIN"."PK_INSTANCETEMPLATEINFO" ON "IMPADMIN"."INSTANCETEMPLATEINFO" (
	"INSTANCETEMPLATEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_KEYPAIR" ON "IMPADMIN"."KEYPAIR" (
	"KEYPAIRID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_OBJSTORAGEINFO" ON "IMPADMIN"."OBJSTORAGEINFO" (
	"OSID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


CREATE UNIQUE INDEX "IMPADMIN"."PK_PI" ON "IMPADMIN"."PHYSICALIMAGE" (
	"IMAGEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_RECORDINFO" ON "IMPADMIN"."DNSRECORDINFO" (
	"RECORDID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_STORAGEGROUPINFO" ON "IMPADMIN"."STORAGEGROUPINFO" (
	"STORAGEGROUPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_STORAGESERVERGROUPINFO" ON "IMPADMIN"."STORAGESERVERGROUPINFO" (
	"STORAGESERVERGROUPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_STORAGESERVERINFO" ON "IMPADMIN"."STORAGESERVERINFO" (
	"STORAGESERVERID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_TARGETPOOL" ON "IMPADMIN"."TARGETPOOL" (
	"TARGETPOOLID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_USERHISTORYINFO" ON "IMPADMIN"."USERHISTORYINFO" (
	"HISTORYID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_WEB_CONSOLE" ON "IMPADMIN"."WEB_CONSOLE" (
	"INSTANCE_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."PK_ZONEINFO" ON "IMPADMIN"."DNSZONEINFO" (
	"ZONEID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."uq_NetworkInfo" ON "IMPADMIN"."NETWORKINFO" (
	"VLANID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."uq_NetworkInfo2" ON "IMPADMIN"."NETWORKINFO" (
	"NETWORKID" ASC,
	"VLANID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."uq_PublicIpInfo" ON "IMPADMIN"."PUBLICIPINFO" (
	"PUBLICIP" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."uq_PublicIpInfo2" ON "IMPADMIN"."PUBLICIPINFO" (
	"VPORTID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."uq_SubnetInfo" ON "IMPADMIN"."SUBNETINFO" (
	"SUBNETID" ASC,
	"VLANID" ASC,
	"NETWORKID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."uq_SubnetInfo2" ON "IMPADMIN"."SUBNETINFO" (
	"NETWORKID" ASC,
	"IPADDR" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."uq_VPortInfo" ON "IMPADMIN"."VPORTINFO" (
	"MAC1" ASC,
	"MAC2" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

CREATE UNIQUE INDEX "IMPADMIN"."uq_VPortInfo3" ON "IMPADMIN"."VPORTINFO" (
	"SUBNETID" ASC,
	"IPADDR" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;


ALTER TABLE "IMPADMIN"."IMAGEMANIFEST" ADD CONSTRAINT "IMAGEMANIFEST_PK"
PRIMARY KEY (
	"IMAGENAME",
	"IMAGEVERSION",
	"IMAGECLASSIFICATION"
);

ALTER TABLE "IMPADMIN"."IMAGE" ADD CONSTRAINT "IMAGE_COMPLEX_PK"
PRIMARY KEY (
	"TENANTID",
	"PROJECTID",
	"IMAGEID"
);



ALTER TABLE "IMPADMIN"."DBINFO" MODIFY 	"TENANTID" NOT NULL;


ALTER TABLE "IMPADMIN"."DNSSERVERINFO" MODIFY 	"INSTANCEID" NOT NULL;

ALTER TABLE "IMPADMIN"."DNSSERVERINFO" MODIFY 	"TENANTID" NOT NULL;

ALTER TABLE "IMPADMIN"."DNSSERVERINFO" MODIFY 	"NETWORKID" NOT NULL;

ALTER TABLE "IMPADMIN"."DNSZONEINFO" MODIFY 	"ZONEUUID" NOT NULL;

ALTER TABLE "IMPADMIN"."DNSZONEINFO" MODIFY 	"NETWORKID" NOT NULL;

ALTER TABLE "IMPADMIN"."DNSRECORDINFO" MODIFY 	"RECORDUUID" NOT NULL;

ALTER TABLE "IMPADMIN"."DNSRECORDINFO" MODIFY 	"ZONEID" NOT NULL;

ALTER TABLE "IMPADMIN"."DNSSERVERINFO" MODIFY 	"TYPE" NOT NULL;

ALTER TABLE "IMPADMIN"."USERHISTORYINFO" MODIFY 	"HISTORYID" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGEMANIFEST" MODIFY 	"IMAGENAME" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGEMANIFEST" MODIFY 	"IMAGEVERSION" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGEMANIFEST" MODIFY 	"IMAGETYPE" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGEMANIFEST" MODIFY 	"SUPPORTOS" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGEMANIFEST" MODIFY 	"IMAGECLASSIFICATION" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGEMANIFEST" MODIFY 	"IMAGEURL" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"TENANTID" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"TENANTUUID" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"TENANTNAME" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"PROJECTID" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"PROJECTUUID" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"PROJECTNAME" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"IMAGEID" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"IMAGEUUID" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"IMAGENAME" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"IMAGETYPE" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"IMAGECLASSIFICATION" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"IMAGEHASH" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"PRODUCTNAME" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"PRODUCTVERSION" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"SUPPORTOS" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"DEFAULTCHECK" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"SHARED" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"STATE" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"UPLOADEDTIME" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"UPLOADERID" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" MODIFY 	"UPLOADERUUID" NOT NULL;

ALTER TABLE "IMPADMIN"."VMIMAGE" ADD 
PRIMARY KEY (
	"IMAGEID"
);

ALTER TABLE "IMPADMIN"."BLOCKSTORAGEINFO" MODIFY 	"BLOCKSTORAGEID" NOT NULL;

ALTER TABLE "IMPADMIN"."BLOCKSTORAGEINFO" ADD 
PRIMARY KEY (
	"BLOCKSTORAGEID"
);


ALTER TABLE "IMPADMIN"."BLOCKSTORAGEMAPPING" ADD 
PRIMARY KEY (
	"BLOCKSTORAGEID"
);


ALTER TABLE "IMPADMIN"."BLOCKSTORAGEIMAGEINFO" ADD 
PRIMARY KEY (
	"IMAGEID"
);

ALTER TABLE "IMPADMIN"."HOSTRESOURCEINFO" MODIFY 	"HOSTID" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTHISTORY" MODIFY 	"ID" NOT NULL;

ALTER TABLE "IMPADMIN"."HOSTHISTORY" ADD 
PRIMARY KEY (
	"ID"
);

ALTER TABLE "IMPADMIN"."PPORTINFO" MODIFY 	"PPORTID" NOT NULL;

ALTER TABLE "IMPADMIN"."PPORTINFO" ADD 
PRIMARY KEY (
	"PPORTID"
);

ALTER TABLE "IMPADMIN"."BLOCKSTORAGESNAPINFO" MODIFY 	"SNAPID" NOT NULL;

ALTER TABLE "IMPADMIN"."LAYER" MODIFY 	"LAYERID" NOT NULL;

ALTER TABLE "IMPADMIN"."LAYER" MODIFY 	"REFCNT" NOT NULL;

ALTER TABLE "IMPADMIN"."LAYER" ADD 
PRIMARY KEY (
	"LAYERID"
);

ALTER TABLE "IMPADMIN"."IMAGELAYERMAPPED" ADD 
PRIMARY KEY (
	"IMAGEID",
	"LAYERID"
);

ALTER TABLE "IMPADMIN"."KEYPAIR" MODIFY 	"KEYPAIRID" NOT NULL;

ALTER TABLE "IMPADMIN"."KEYPAIRMAPPING" MODIFY 	"INSTANCEID" NOT NULL;

ALTER TABLE "IMPADMIN"."KEYPAIRMAPPING" MODIFY 	"KEYPAIRID" NOT NULL;

ALTER TABLE "IMPADMIN"."KEYPAIRMAPPING" MODIFY 	"TENANTID" NOT NULL;

ALTER TABLE "IMPADMIN"."KEYPAIRMAPPING" MODIFY 	"PROJECTID" NOT NULL;

ALTER TABLE "IMPADMIN"."WEB_CONSOLE" MODIFY 	"INSTANCE_ID" NOT NULL;

ALTER TABLE "IMPADMIN"."TARGETPOOL" MODIFY 	"TARGETPOOLID" NOT NULL;

ALTER TABLE "IMPADMIN"."TARGETPOOL" MODIFY 	"TENANTID" NOT NULL;

ALTER TABLE "IMPADMIN"."TARGETPOOL" MODIFY 	"PROJECTID" NOT NULL;

ALTER TABLE "IMPADMIN"."TARGETPOOL" ADD 
PRIMARY KEY (
	"TARGETPOOLID"
);

ALTER TABLE "IMPADMIN"."TARGETINSTANCE" MODIFY 	"INSTANCEID" NOT NULL;

ALTER TABLE "IMPADMIN"."TARGETINSTANCE" MODIFY 	"TARGETPOOLID" NOT NULL;

ALTER TABLE "IMPADMIN"."TARGETINSTANCE" ADD 
PRIMARY KEY (
	"INSTANCEID",
	"TARGETPOOLID"
);

ALTER TABLE "IMPADMIN"."COMMGROUPINFO" MODIFY 	"COMMGROUPUUID" NOT NULL;

ALTER TABLE "IMPADMIN"."COMMGROUPINFO" MODIFY 	"TENANTID" NOT NULL;

ALTER TABLE "IMPADMIN"."COMMGROUPINFO" MODIFY 	"PROJECTID" NOT NULL;

ALTER TABLE "IMPADMIN"."COMMGROUPINFO" MODIFY 	"NAME" NOT NULL;

ALTER TABLE "IMPADMIN"."COMMGROUPINFO" ADD 
PRIMARY KEY (
	"COMMGROUPID"
);

ALTER TABLE "IMPADMIN"."COMMGROUPINFO" ADD 
UNIQUE (
	"COMMGROUPUUID"
);

ALTER TABLE "IMPADMIN"."INSTANCEINFO" ADD 
PRIMARY KEY (
	"INSTANCEID"
);

ALTER TABLE "IMPADMIN"."VPORTINFO" MODIFY 	"VPORTID" NOT NULL;

ALTER TABLE "IMPADMIN"."VPORTINFO" MODIFY 	"MAC1" NOT NULL;

ALTER TABLE "IMPADMIN"."VPORTINFO" MODIFY 	"MAC2" NOT NULL;

ALTER TABLE "IMPADMIN"."VPORTINFO" MODIFY 	"VLANID" NOT NULL;

ALTER TABLE "IMPADMIN"."VPORTINFO" MODIFY 	"NETWORKID" NOT NULL;

ALTER TABLE "IMPADMIN"."VPORTINFO" MODIFY 	"IPADDR" NOT NULL;

ALTER TABLE "IMPADMIN"."VPORTINFO" MODIFY 	"MACADDR" NOT NULL;

ALTER TABLE "IMPADMIN"."VPORTINFO" MODIFY 	"SUBNETID" NOT NULL;

ALTER TABLE "IMPADMIN"."VPORTINFO" MODIFY 	"VPORTUUID" NOT NULL;

ALTER TABLE "IMPADMIN"."VPORTINFO" MODIFY 	"NAME" NOT NULL;

ALTER TABLE "IMPADMIN"."VPORTINFO" MODIFY 	"NETWORKTYPE" NOT NULL;

ALTER TABLE "IMPADMIN"."VPORTINFO" ADD 
PRIMARY KEY (
	"VPORTID"
);

ALTER TABLE "IMPADMIN"."VPORTINFO" ADD 
UNIQUE (
	"VPORTUUID"
);

ALTER TABLE "IMPADMIN"."PUBLICIPINFO" MODIFY 	"PUBLICIP" NOT NULL;

ALTER TABLE "IMPADMIN"."PUBLICIPINFO" MODIFY 	"PUBLICIPID" NOT NULL;

ALTER TABLE "IMPADMIN"."PUBLICIPINFO" MODIFY 	"PUBLICIPUUID" NOT NULL;

ALTER TABLE "IMPADMIN"."PUBLICIPINFO" ADD 
PRIMARY KEY (
	"PUBLICIPID"
);

ALTER TABLE "IMPADMIN"."PUBLICIPINFO" ADD 
UNIQUE (
	"PUBLICIPUUID"
);

ALTER TABLE "IMPADMIN"."HOSTINFO" ADD 
PRIMARY KEY (
	"HOSTID"
);

ALTER TABLE "IMPADMIN"."VSWITCHINFO" MODIFY 	"VLANID" NOT NULL;

ALTER TABLE "IMPADMIN"."VSWITCHINFO" MODIFY 	"HOSTID" NOT NULL;

ALTER TABLE "IMPADMIN"."PHYSICALIMAGE" MODIFY 	"IMAGEID" NOT NULL;

ALTER TABLE "IMPADMIN"."PHYSICALIMAGE" MODIFY 	"IMAGEUUID" NOT NULL;

ALTER TABLE "IMPADMIN"."PHYSICALIMAGE" MODIFY 	"PRODUCTNAME" NOT NULL;

ALTER TABLE "IMPADMIN"."PHYSICALIMAGE" MODIFY 	"PRODUCTVERSION" NOT NULL;

ALTER TABLE "IMPADMIN"."DNSZONEINFO" MODIFY 	"ZONEID" NOT NULL;

ALTER TABLE "IMPADMIN"."DNSZONEINFO" MODIFY 	"DOMAINNAME" NOT NULL;

ALTER TABLE "IMPADMIN"."DNSRECORDINFO" MODIFY 	"RECORDID" NOT NULL;

ALTER TABLE "IMPADMIN"."DNSRECORDINFO" MODIFY 	"DATATYPE" NOT NULL;

ALTER TABLE "IMPADMIN"."DNSRECORDINFO" MODIFY 	"TTL" NOT NULL;

ALTER TABLE "IMPADMIN"."DNSRECORDINFO" MODIFY 	"DATA" NOT NULL;

ALTER TABLE "IMPADMIN"."AUTOSCALEINFO" ADD 
PRIMARY KEY (
	"AUTOSCALEID"
);

ALTER TABLE "IMPADMIN"."VSWITCHINFO" MODIFY 	"NAME" NOT NULL;

ALTER TABLE "IMPADMIN"."VSWITCHINFO" MODIFY 	"PORTNAME" NOT NULL;

ALTER TABLE "IMPADMIN"."VSWITCHINFO" ADD 
PRIMARY KEY (
	"VLANID",
	"HOSTID"
);

ALTER TABLE "IMPADMIN"."INSTANCECOMMGROUPINFO" MODIFY 	"INSTANCEID" NOT NULL;

ALTER TABLE "IMPADMIN"."INSTANCECOMMGROUPINFO" MODIFY 	"COMMGROUPID" NOT NULL;

ALTER TABLE "IMPADMIN"."INSTANCECOMMGROUPINFO" ADD 
PRIMARY KEY (
	"INSTANCEID",
	"COMMGROUPID"
);

ALTER TABLE "IMPADMIN"."IMAGESTATEINFO" MODIFY 	"IMAGEID" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGESTATEINFO" MODIFY 	"TENANTID" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGESTATEINFO" MODIFY 	"STATEFLAG" NOT NULL;

ALTER TABLE "IMPADMIN"."FILESTORAGEINFO" MODIFY 	"FILESTORAGEID" NOT NULL;

ALTER TABLE "IMPADMIN"."FILESTORAGEINFO" ADD 
PRIMARY KEY (
	"FILESTORAGEID"
);

ALTER TABLE "IMPADMIN"."FILESTORAGEMAPPING" MODIFY 	"INSTANCEID" NOT NULL;

ALTER TABLE "IMPADMIN"."FILESTORAGEMAPPING" MODIFY 	"FILESTORAGEID" NOT NULL;

ALTER TABLE "IMPADMIN"."INNERFILESYSTEMINFO" MODIFY 	"INNERFILESYSTEMID" NOT NULL;

ALTER TABLE "IMPADMIN"."INNERFILESYSTEMINFO" MODIFY 	"STORAGEUNITID" NOT NULL;

ALTER TABLE "IMPADMIN"."INNERFILESYSTEMINFO" MODIFY 	"ROOTPATHNAME" NOT NULL;

ALTER TABLE "IMPADMIN"."DBINFO" MODIFY 	"DBID" NOT NULL;

ALTER TABLE "IMPADMIN"."DBINFO" MODIFY 	"STORAGESERVERGROUPID" NOT NULL;

ALTER TABLE "IMPADMIN"."DBINFO" MODIFY 	"TOTALSIZE" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEGROUPINFO" MODIFY 	"STORAGEGROUPID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEGROUPINFO" MODIFY 	"TOTALSIZE" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEGROUPINFO" MODIFY 	"TOTALSTORAGENUMBER" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEGROUPINFO" MODIFY 	"USAGE" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERGROUPINFO" MODIFY 	"STORAGESERVERGROUPID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERGROUPINFO" MODIFY 	"STORAGEGROUPID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERGROUPINFO" MODIFY 	"TENANTID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERINFO" MODIFY 	"STORAGESERVERID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERINFO" MODIFY 	"STORAGEUNITID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERINFO" MODIFY 	"STORAGESERVERGROUPID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERINFO" MODIFY 	"STORAGESERVERIP" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGESERVERINFO" MODIFY 	"STORAGESERVERPORT" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEUNITINFO" MODIFY 	"STORAGEUNITID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEUNITINFO" MODIFY 	"STORAGENODEID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEUNITINFO" MODIFY 	"STORAGEGROUPID" NOT NULL;

ALTER TABLE "IMPADMIN"."STORAGEUNITINFO" MODIFY 	"TOTALSIZE" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGELAYERMAPPED" MODIFY 	"IMAGEID" NOT NULL;

ALTER TABLE "IMPADMIN"."IMAGELAYERMAPPED" MODIFY 	"LAYERID" NOT NULL;

ALTER TABLE "IMPADMIN"."NODEIMAGE" MODIFY 	"NODEIP" NOT NULL;

ALTER TABLE "IMPADMIN"."NODEIMAGE" MODIFY 	"IMAGEID" NOT NULL;

ALTER TABLE "IMPADMIN"."NODEIMAGE" MODIFY 	"REFCNT" NOT NULL;

ALTER TABLE "IMPADMIN"."NETWORKINFO" MODIFY 	"NETWORKID" NOT NULL;

ALTER TABLE "IMPADMIN"."NETWORKINFO" MODIFY 	"VLANID" NOT NULL;

ALTER TABLE "IMPADMIN"."NETWORKINFO" MODIFY 	"NETWORKUUID" NOT NULL;

ALTER TABLE "IMPADMIN"."NETWORKINFO" MODIFY 	"NAME" NOT NULL;

ALTER TABLE "IMPADMIN"."NETWORKINFO" MODIFY 	"TYPE" NOT NULL;

ALTER TABLE "IMPADMIN"."NETWORKINFO" ADD 
PRIMARY KEY (
	"NETWORKID"
);

ALTER TABLE "IMPADMIN"."NETWORKINFO" ADD 
UNIQUE (
	"NETWORKUUID"
);

ALTER TABLE "IMPADMIN"."SUBNETINFO" MODIFY 	"SUBNETID" NOT NULL;

ALTER TABLE "IMPADMIN"."SUBNETINFO" MODIFY 	"NETWORKID" NOT NULL;

ALTER TABLE "IMPADMIN"."SUBNETINFO" MODIFY 	"SUBNETUUID" NOT NULL;

ALTER TABLE "IMPADMIN"."SUBNETINFO" MODIFY 	"IPADDR" NOT NULL;

ALTER TABLE "IMPADMIN"."SUBNETINFO" MODIFY 	"NETMASK" NOT NULL;

ALTER TABLE "IMPADMIN"."SUBNETINFO" MODIFY 	"CIDR" NOT NULL;

ALTER TABLE "IMPADMIN"."SUBNETINFO" MODIFY 	"VLANID" NOT NULL;

ALTER TABLE "IMPADMIN"."SUBNETINFO" MODIFY 	"NAME" NOT NULL;

ALTER TABLE "IMPADMIN"."SUBNETINFO" MODIFY 	"TYPE" NOT NULL;

ALTER TABLE "IMPADMIN"."SUBNETINFO" ADD 
PRIMARY KEY (
	"SUBNETID"
);

ALTER TABLE "IMPADMIN"."SUBNETINFO" ADD 
UNIQUE (
	"SUBNETUUID"
);

ALTER TABLE "IMPADMIN"."COMMGROUPINFO" MODIFY 	"COMMGROUPID" NOT NULL;

ALTER TABLE "IMPADMIN"."METERING" ADD CONSTRAINT "METERINGUNIQUE"
PRIMARY KEY (
	"TENANTID",
	"PROJECTID",
	"METERINGTYPE",
	"VOLUMETYPE",
	"METERINGDATE"
);

ALTER TABLE "IMPADMIN"."NODEIMAGE" ADD CONSTRAINT "NODEIMAGE_COMPLEX_PK"
PRIMARY KEY (
	"NODEIP",
	"IMAGEID"
);


ALTER TABLE "IMPADMIN"."BLOCKSTORAGESNAPINFO" ADD CONSTRAINT "PK_BLOCKSTORAGESNAPINFO"
PRIMARY KEY (
	"SNAPID"
);

ALTER TABLE "IMPADMIN"."DBINFO" ADD CONSTRAINT "PK_DBINFO"
PRIMARY KEY (
	"DBID"
);

ALTER TABLE "IMPADMIN"."FILESTORAGEMAPPING" ADD CONSTRAINT "PK_FILESTORAGEMAPPING"
PRIMARY KEY (
	"INSTANCEID",
	"FILESTORAGEID"
);

ALTER TABLE "IMPADMIN"."INNERFILESYSTEMINFO" ADD CONSTRAINT "PK_INNERFILESYSTEMINFO"
PRIMARY KEY (
	"INNERFILESYSTEMID"
);

ALTER TABLE "IMPADMIN"."INSTANCETEMPLATEINFO" ADD CONSTRAINT "PK_INSTANCETEMPLATEINFO"
PRIMARY KEY (
	"INSTANCETEMPLATEID"
);

ALTER TABLE "IMPADMIN"."KEYPAIR" ADD CONSTRAINT "PK_KEYPAIR"
PRIMARY KEY (
	"KEYPAIRID"
);

ALTER TABLE "IMPADMIN"."OBJSTORAGEINFO" ADD CONSTRAINT "PK_OBJSTORAGEINFO"
PRIMARY KEY (
	"OSID"
);

ALTER TABLE "IMPADMIN"."PHYSICALIMAGE" ADD CONSTRAINT "PK_PI"
PRIMARY KEY (
	"IMAGEID"
);

ALTER TABLE "IMPADMIN"."DNSRECORDINFO" ADD CONSTRAINT "PK_RECORDINFO"
PRIMARY KEY (
	"RECORDID"
);

ALTER TABLE "IMPADMIN"."STORAGEGROUPINFO" ADD CONSTRAINT "PK_STORAGEGROUPINFO"
PRIMARY KEY (
	"STORAGEGROUPID"
);

ALTER TABLE "IMPADMIN"."STORAGESERVERGROUPINFO" ADD CONSTRAINT "PK_STORAGESERVERGROUPINFO"
PRIMARY KEY (
	"STORAGESERVERGROUPID"
);

ALTER TABLE "IMPADMIN"."STORAGESERVERINFO" ADD CONSTRAINT "PK_STORAGESERVERINFO"
PRIMARY KEY (
	"STORAGESERVERID"
);

ALTER TABLE "IMPADMIN"."USERHISTORYINFO" ADD CONSTRAINT "PK_USERHISTORYINFO"
PRIMARY KEY (
	"HISTORYID"
);

ALTER TABLE "IMPADMIN"."WEB_CONSOLE" ADD CONSTRAINT "PK_WEB_CONSOLE"
PRIMARY KEY (
	"INSTANCE_ID"
);

ALTER TABLE "IMPADMIN"."DNSZONEINFO" ADD CONSTRAINT "PK_ZONEINFO"
PRIMARY KEY (
	"ZONEID"
);

ALTER TABLE "IMPADMIN"."NETWORKINFO" ADD CONSTRAINT "uq_NetworkInfo"
UNIQUE (
	"VLANID"
);

ALTER TABLE "IMPADMIN"."NETWORKINFO" ADD CONSTRAINT "uq_NetworkInfo2"
UNIQUE (
	"NETWORKID",
	"VLANID"
);

ALTER TABLE "IMPADMIN"."PUBLICIPINFO" ADD CONSTRAINT "uq_PublicIpInfo"
UNIQUE (
	"PUBLICIP"
);

ALTER TABLE "IMPADMIN"."PUBLICIPINFO" ADD CONSTRAINT "uq_PublicIpInfo2"
UNIQUE (
	"VPORTID"
);

ALTER TABLE "IMPADMIN"."SUBNETINFO" ADD CONSTRAINT "uq_SubnetInfo"
UNIQUE (
	"SUBNETID",
	"VLANID",
	"NETWORKID"
);

ALTER TABLE "IMPADMIN"."SUBNETINFO" ADD CONSTRAINT "uq_SubnetInfo2"
UNIQUE (
	"NETWORKID",
	"IPADDR"
);

ALTER TABLE "IMPADMIN"."VPORTINFO" ADD CONSTRAINT "uq_VPortInfo"
UNIQUE (
	"MAC1",
	"MAC2"
);

ALTER TABLE "IMPADMIN"."VPORTINFO" ADD CONSTRAINT "uq_VPortInfo3"
UNIQUE (
	"SUBNETID",
	"IPADDR"
);

ALTER TABLE "IMPADMIN"."TARGETINSTANCE" ADD CONSTRAINT "BHKTARGET"
FOREIGN KEY (
	"TARGETPOOLID"
) REFERENCES "IMPADMIN"."TARGETPOOL" (
	"TARGETPOOLID"
);

ALTER TABLE "IMPADMIN"."NODEIMAGE" ADD CONSTRAINT "FK3_PI"
FOREIGN KEY (
	"IMAGEID"
) REFERENCES "IMPADMIN"."PHYSICALIMAGE" (
	"IMAGEID"
);

ALTER TABLE "IMPADMIN"."BLOCKSTORAGEIMAGEINFO" ADD CONSTRAINT "FK_01"
FOREIGN KEY (
	"SNAPID"
) REFERENCES "IMPADMIN"."BLOCKSTORAGESNAPINFO" (
	"SNAPID"
);

ALTER TABLE "IMPADMIN"."BLOCKSTORAGEMAPPING" ADD CONSTRAINT "FK_BLOCKSTORAGEMAPPING"
FOREIGN KEY (
	"BLOCKSTORAGEID"
) REFERENCES "IMPADMIN"."BLOCKSTORAGEINFO" (
	"BLOCKSTORAGEID"
);

ALTER TABLE "IMPADMIN"."HOSTRESOURCEINFO" ADD CONSTRAINT "FK_HOSTRESOURCE_HOSTID"
FOREIGN KEY (
	"HOSTID"
) REFERENCES "IMPADMIN"."HOSTINFO" (
	"HOSTID"
);

ALTER TABLE "IMPADMIN"."BLOCKSTORAGEMAPPING" ADD CONSTRAINT "FK_INSTANCEMAPPING"
FOREIGN KEY (
	"INSTANCEID"
) REFERENCES "IMPADMIN"."INSTANCEINFO" (
	"INSTANCEID"
);

ALTER TABLE "IMPADMIN"."PPORTINFO" ADD CONSTRAINT "FK_PPORTINFO"
FOREIGN KEY (
	"HOSTID"
) REFERENCES "IMPADMIN"."HOSTINFO" (
	"HOSTID"
);

ALTER TABLE "IMPADMIN"."DNSRECORDINFO" ADD CONSTRAINT "FK_RECORDINFO"
FOREIGN KEY (
	"ZONEID"
) REFERENCES "IMPADMIN"."DNSZONEINFO" (
	"ZONEID"
);

ALTER TABLE "IMPADMIN"."SUBNETINFO" ADD CONSTRAINT "FK_SUBNETINFO_NETWORKINFO"
FOREIGN KEY (
	"NETWORKID",
	"VLANID"
) REFERENCES "IMPADMIN"."NETWORKINFO" (
	"NETWORKID",
	"VLANID"
);

ALTER TABLE "IMPADMIN"."OBJSTORAGEGATEWAYINFO" ADD 
FOREIGN KEY (
	"HOSTID"
) REFERENCES "IMPADMIN"."HOSTINFO" (
	"HOSTID"
);

ALTER TABLE "IMPADMIN"."TARGETINSTANCE" ADD CONSTRAINT "INSTANCE_TARGETINSTANCE"
FOREIGN KEY (
	"INSTANCEID"
) REFERENCES "IMPADMIN"."INSTANCEINFO" (
	"INSTANCEID"
);

ALTER TABLE "IMPADMIN"."INSTANCECOMMGROUPINFO" ADD CONSTRAINT "fk_IcgInfo_CgInfo"
FOREIGN KEY (
	"COMMGROUPID"
) REFERENCES "IMPADMIN"."COMMGROUPINFO" (
	"COMMGROUPID"
);

ALTER TABLE "IMPADMIN"."INSTANCECOMMGROUPINFO" ADD CONSTRAINT "fk_IcgInfo_InstanceInfo"
FOREIGN KEY (
	"INSTANCEID"
) REFERENCES "IMPADMIN"."INSTANCEINFO" (
	"INSTANCEID"
);

ALTER TABLE "IMPADMIN"."PUBLICIPINFO" ADD CONSTRAINT "fk_PublicIpInfo_PortInfo"
FOREIGN KEY (
	"VPORTID"
) REFERENCES "IMPADMIN"."VPORTINFO" (
	"VPORTID"
);

ALTER TABLE "IMPADMIN"."VPORTINFO" ADD CONSTRAINT "fk_VPortInfo_InstanceInfo"
FOREIGN KEY (
	"INSTANCEID"
) REFERENCES "IMPADMIN"."INSTANCEINFO" (
	"INSTANCEID"
);

ALTER TABLE "IMPADMIN"."VPORTINFO" ADD CONSTRAINT "fk_VPortInfo_SubnetInfo"
FOREIGN KEY (
	"SUBNETID",
	"VLANID",
	"NETWORKID"
) REFERENCES "IMPADMIN"."SUBNETINFO" (
	"SUBNETID",
	"VLANID",
	"NETWORKID"
);

ALTER TABLE "IMPADMIN"."VSWITCHINFO" ADD CONSTRAINT "fk_VswitchInfo_HostInfo"
FOREIGN KEY (
	"HOSTID"
) REFERENCES "IMPADMIN"."HOSTINFO" (
	"HOSTID"
);

ALTER TABLE "IMPADMIN"."VSWITCHINFO" ADD CONSTRAINT "fk_VswitchInfo_NetworkInfo"
FOREIGN KEY (
	"VLANID"
) REFERENCES "IMPADMIN"."NETWORKINFO" (
	"VLANID"
);

commit;
exit
