/* REMOVE ALL TABLES, INDEXES */
/* 1 */ DROP TABLE "FIREWALL";
/* 2 */ DROP TABLE "GATEWAY";
/* 3 */ DROP TABLE "LBTARGETINSTANCEINFO";
/* 4 */ DROP TABLE "LBRULEINFO";
/* 5 */ DROP TABLE "HOSTGROUPHOSTMAPPING";
/* 6 */ DROP TABLE "RULEGROUPRULEMAPPING";
/* 7 */ DROP TABLE "GROUPMAPPING";
/* 8 */ DROP TABLE "HOSTGROUPINFO";
/* 9 */ DROP TABLE "RULEGROUPINFO";
/* 10 */ DROP TABLE "APPLIEDRULEINFO";
/* 11 */ DROP TABLE "NFTRULEINFO";
/* 12 */ DROP TABLE "APPLIEDCHAININFO";
/* 13 */ DROP TABLE "APPLIEDTABLEINFO";
/* 14 */ DROP TABLE "NFTHOSTINTERFACEINFO";
/* 15 */ DROP TABLE "NFTHOSTINFO"; 

/* 15. NFTHOSTINFO TABLE */
CREATE TABLE NFTHOSTINFO (
	NFTHOSTID NUMBER NOT NULL,
	FARM VARCHAR(20),
	NICKNAME VARCHAR(50),
	ACCESSID VARCHAR(20),
	ACCESSPASSWORD VARCHAR(20),
	ACCESSINTERFACEID NUMBER,
	STATUS VARCHAR(10),
	CREATEDTIME TIMESTAMP(6),
	UPDATEDTIME TIMESTAMP(6)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX PK_NFTHOSTINFO ON NFTHOSTINFO (
	NFTHOSTID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE NFTHOSTINFO ADD CONSTRAINT PK_NFTHOSTINFO
PRIMARY KEY (
	NFTHOSTID
);

/* 14. NFTHOSTINTERFACEINFO TABLE */
CREATE TABLE NFTHOSTINTERFACEINFO (
	NFTHOSTINTERFACEID NUMBER NOT NULL,
	NFTHOSTID NUMBER,
	PHYSICALNAME VARCHAR(20),
	NICKNAME VARCHAR(50),
	IPADDRESS VARCHAR(20),
	NETWORKTYPE VARCHAR(1),
	TRUSTZONE VARCHAR(10),
	STATUS VARCHAR(10),
	CREATEDTIME TIMESTAMP(6),
	UPDATEDTIME TIMESTAMP(6),
	NetMask VARCHAR(20)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX PK_NFTHOSTINTERFACEINFO ON NFTHOSTINTERFACEINFO (
	NFTHOSTINTERFACEID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE NFTHOSTINTERFACEINFO ADD CONSTRAINT PK_NFTHOSTINTERFACEINFO
PRIMARY KEY (
	NFTHOSTINTERFACEID
);

ALTER TABLE NFTHOSTINTERFACEINFO ADD CONSTRAINT FK_NHI_NFTHOSTID
FOREIGN KEY (
	NFTHOSTID
) REFERENCES NFTHOSTINFO (
	NFTHOSTID
);

/* 13. APPLIEDTABLEINFO TABLE */
CREATE TABLE APPLIEDTABLEINFO (
	APPLIEDTABLEID NUMBER NOT NULL,
	NFTHOSTID NUMBER,
	NFTNAME VARCHAR(20),
	FAMILY VARCHAR(10),
	CREATEDTIME TIMESTAMP(6),
	UPDATEDTIME TIMESTAMP(6)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX PK_APPLIEDTABLEINFO ON APPLIEDTABLEINFO (
	APPLIEDTABLEID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE APPLIEDTABLEINFO ADD CONSTRAINT PK_APPLIEDTABLEINFO
PRIMARY KEY (
	APPLIEDTABLEID
);

ALTER TABLE APPLIEDTABLEINFO ADD CONSTRAINT FK_TABLE_NFTHOSTID
FOREIGN KEY (
	NFTHOSTID
) REFERENCES NFTHOSTINFO (
	NFTHOSTID
);

/* 12. APPLIEDCHAININFO TABLE */
CREATE TABLE APPLIEDCHAININFO (
	APPLIEDCHAINID NUMBER NOT NULL,
	APPLIEDTABLEID NUMBER,
	NFTCHAINNAME VARCHAR(20),
	HOOK VARCHAR(20),
	PRIORITY NUMBER,
	TYPE NUMBER,
	POLICY NUMBER,
	CREATEDTIME TIMESTAMP(6),
	UPDATEDTIME TIMESTAMP(6)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX PK_APPLIEDCHAININFO ON APPLIEDCHAININFO (
	APPLIEDCHAINID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE APPLIEDCHAININFO ADD CONSTRAINT PK_APPLIEDCHAININFO
PRIMARY KEY (
	APPLIEDCHAINID
);

ALTER TABLE APPLIEDCHAININFO ADD CONSTRAINT FK_CHAIN_TABLEID
FOREIGN KEY (
	APPLIEDTABLEID
) REFERENCES APPLIEDTABLEINFO (
	APPLIEDTABLEID
);

/* 11. NFTRULEINFO TABLE */
CREATE TABLE NFTRULEINFO (
	NFTRULEID NUMBER NOT NULL,
	RULESTRING VARCHAR(255),
	NETTYPE NUMBER
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX PK_NFTRULEINFO ON NFTRULEINFO (
	NFTRULEID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE NFTRULEINFO ADD CONSTRAINT PK_NFTRULEINFO
PRIMARY KEY (
	NFTRULEID
);

/* 10. APPLIEDRULEINFO TABLE */
CREATE TABLE APPLIEDRULEINFO (
	APPLIEDRULEID NUMBER NOT NULL,
	APPLIEDCHAINID NUMBER,
	NFTRULEID NUMBER,
	HANDLE NUMBER,
	SEQNUMBER NUMBER,
	COUNTER NUMBER,
	CREATEDTIME TIMESTAMP(6),
	UPDATEDTIME TIMESTAMP(6)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX PK_APPLIEDRULEINFO ON APPLIEDRULEINFO (
	APPLIEDRULEID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE APPLIEDRULEINFO ADD CONSTRAINT PK_APPLIEDRULEINFO
PRIMARY KEY (
	APPLIEDRULEID
);

ALTER TABLE APPLIEDRULEINFO ADD CONSTRAINT FK_RULE_CHAINID
FOREIGN KEY (
	APPLIEDCHAINID
) REFERENCES APPLIEDCHAININFO (
	APPLIEDCHAINID
);

ALTER TABLE APPLIEDRULEINFO ADD CONSTRAINT FK_RULE_NFTRULEID
FOREIGN KEY (
	NFTRULEID
) REFERENCES NFTRULEINFO (
	NFTRULEID
);

/* 9. RULEGROUPINFO */
CREATE TABLE RULEGROUPINFO (
	RULEGROUPID NUMBER NOT NULL,
	NICKNAME VARCHAR(50),
	FUNCTIONTYPE NUMBER,
	CREATEDTIME TIMESTAMP(6),
	UPDATEDTIME TIMESTAMP(6)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX PK_RULEGROUPINFO ON RULEGROUPINFO (
	RULEGROUPID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE RULEGROUPINFO ADD CONSTRAINT PK_RULEGROUPINFO
PRIMARY KEY (
	RULEGROUPID
);

/* 8. HOSTGROUPINFO TABLE */
CREATE TABLE HOSTGROUPINFO (
	HOSTGROUPID NUMBER NOT NULL,
	NICKNAME VARCHAR(50),
	CREATEDTIME TIMESTAMP(6),
	UPDATEDTIME TIMESTAMP(6)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX PK_HOSTGROUPINFO ON HOSTGROUPINFO (
	HOSTGROUPID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE HOSTGROUPINFO ADD CONSTRAINT PK_HOSTGROUPINFO
PRIMARY KEY (
	HOSTGROUPID
);

/* 7. GROUPMAPPING TABLE */
CREATE TABLE GROUPMAPPING (
	HOSTGROUPID NUMBER,
	RULEGROUPID NUMBER
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

ALTER TABLE GROUPMAPPING ADD CONSTRAINT FK_GROUPMAPPING_HOSTGROUPID
FOREIGN KEY (
	HOSTGROUPID
) REFERENCES HOSTGROUPINFO (
	HOSTGROUPID
);

ALTER TABLE GROUPMAPPING ADD CONSTRAINT FK_GROUPMAPPING_RULEGROUPID
FOREIGN KEY (
	RULEGROUPID
) REFERENCES RULEGROUPINFO (
	RULEGROUPID
);

/* 6. RULEGROUPRULEMAPPING TABLE */
CREATE TABLE RULEGROUPRULEMAPPING (
	RULEGROUPID NUMBER,
	NFTRULEID NUMBER,
	SEQNUMBER NUMBER
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

ALTER TABLE RULEGROUPRULEMAPPING ADD CONSTRAINT FK_RGRM_NFTRULEID
FOREIGN KEY (
	NFTRULEID
) REFERENCES NFTRULEINFO (
	NFTRULEID
);

ALTER TABLE RULEGROUPRULEMAPPING ADD CONSTRAINT FK_RGRM_RULEGROUPID
FOREIGN KEY (
	RULEGROUPID
) REFERENCES RULEGROUPINFO (
	RULEGROUPID
);

/* 5. HOSTGROUPGHOSTMAPPING TABLE */
CREATE TABLE HOSTGROUPHOSTMAPPING (
	HOSTGROUPID NUMBER NOT NULL,
	NFTHOSTID NUMBER NOT NULL
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

ALTER TABLE HOSTGROUPHOSTMAPPING ADD CONSTRAINT FK_HGHM_NFTHOSTID
FOREIGN KEY (
	NFTHOSTID
) REFERENCES NFTHOSTINFO (
	NFTHOSTID
);

ALTER TABLE HOSTGROUPHOSTMAPPING ADD CONSTRAINT FK_HGHM_HOSTGROUPID
FOREIGN KEY (
	HOSTGROUPID
) REFERENCES HOSTGROUPINFO (
	HOSTGROUPID
);


/* 4. LBRULEINFO TABLE */
CREATE TABLE LBRULEINFO (
	LBRULEUUID VARCHAR(30),
	LBRULEID NUMBER NOT NULL,
	PREAPPLIEDRULEID NUMBER,
	POSTAPPLIEDRULEID NUMBER,
	NFTRULEID NUMBER,
	VIPADDR VARCHAR(30),
	VIPPORT NUMBER(7),
	ISSTATEFUL NUMBER(1),
	ISDSR NUMBER(1),
	MOD NUMBER(5),
	VMACADDR VARCHAR(30),
	NFTHOSTID NUMBER,
	STATUS VARCHAR(20),
	CONTAINERPORT NUMBER,
	CREATEDTIME TIMESTAMP(6),
	UPDATEDTIME TIMESTAMP(6)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX PK_LBRULEINFO ON LBRULEINFO (
	LBRULEID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE LBRULEINFO ADD CONSTRAINT PK_LBRULEINFO
PRIMARY KEY (
	LBRULEID
);


/* 3. LBTARGETINSTANCEINFO TABLE */
CREATE TABLE LBTARGETINSTANCEINFO (
	TARGETINSTANCEID NUMBER NOT NULL,
	LBRULEID NUMBER,
	TIPADDR VARCHAR(30),
	TIPPORT NUMBER(7),
	WEIGHT NUMBER(3),
	TMACADDR VARCHAR(30),
	INSTANCEID NUMBER,
	STATUS VARCHAR(20),
	CREATEDTIME TIMESTAMP(6),
	UPDATEDTIME TIMESTAMP(6)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX PK_LBTARGETINSTANCEINFO ON LBTARGETINSTANCEINFO (
	TARGETINSTANCEID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE LBTARGETINSTANCEINFO ADD CONSTRAINT PK_LBTARGETINSTANCEINFO
PRIMARY KEY (
	TARGETINSTANCEID
);

ALTER TABLE LBTARGETINSTANCEINFO ADD CONSTRAINT FK_LBRULE_TARGETINSTANCE
FOREIGN KEY (
	LBRULEID
) REFERENCES LBRULEINFO (
	LBRULEID
);


/* 2. GATEWAY TABLE */
CREATE TABLE GATEWAY (
	GWRULEID NUMBER NOT NULL,
	ORIGINIP VARCHAR(255),
	NATIP VARCHAR(34),
	ORIGINPORT NUMBER,
	NATPORT NUMBER,
	NATTYPE NUMBER,
	PREAPPLIEDRULEID NUMBER,
	POSTAPPLIEDRULEID NUMBER,
	NFTHOSTID NUMBER,
	PROTOCOL VARCHAR(30)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX PK_GATEWAY ON GATEWAY (
	GWRULEID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE GATEWAY ADD CONSTRAINT PK_GATEWAY
PRIMARY KEY (
	GWRULEID
);

/* 1. FIREWALL TABLE */
CREATE TABLE FIREWALL (
	FIREWALLRULEID NUMBER NOT NULL,
	NFTHOSTID NUMBER,
	NFTRULEID NUMBER,
	APPLIEDRULEID NUMBER,
	CHAINNAME VARCHAR(20),
	SRCIP VARCHAR(255),
	DSTIP VARCHAR(255),
	SRCPORT VARCHAR(50),
	DSTPORT VARCHAR(50),
	PROTOCOL VARCHAR(50),
	ACTION VARCHAR(30),
	REJECTTYPE VARCHAR(50)
)
TABLESPACE USR
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX PK_FIREWALL ON FIREWALL (
	FIREWALLRULEID ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE FIREWALL ADD CONSTRAINT PK_FIREWALL
PRIMARY KEY (
	FIREWALLRULEID
);

ALTER TABLE FIREWALL ADD CONSTRAINT FK_FIREWALL_NFTRULEID
FOREIGN KEY (
	NFTRULEID
) REFERENCES NFTRULEINFO (
	NFTRULEID
);

commit;
exit
