/* BASE DATA FOR LB */
INSERT INTO NFTHOSTINFO(NFTHOSTID, FARM, NICKNAME, ACCESSID, ACCESSPASSWORD, ACCESSINTERFACEID, STATUS) VALUES(2864434397, 'undefined', 'base', 'root', 'tmax@23', 0, 'Active');

commit;
exit
