/* REMOVE All TABLES, INDEXES */
TRUNCATE TABLE "AGGREGATESTATSENTRY";
/* 1 */	DROP TABLE "AGGREGATESTATSENTRY";
TRUNCATE TABLE "PORTSTATSENTRY";
/* 2 */	DROP TABLE "PORTSTATSENTRY";
TRUNCATE TABLE "FLOWSTATSENTRY";
/* 3 */	DROP TABLE "FLOWSTATSENTRY";
/* 4 */	DROP TABLE "FLOWENTRY";
/* 5 */	DROP TABLE "GROUPENTRY";
/* 6 */	DROP TABLE "LINKENTRY";
/* 7 */	DROP TABLE "PORTENTRY";
/* 8 */	DROP TABLE "SWITCHENTRY";
/* 9 */	DROP TABLE "GATEWAYINFO";
/* 10*/ DROP TABLE "STATSINFO";
/* 11*/ DROP TABLE "ARPHOSTINFO";
/* 12*/ DROP TABLE "EVENTINFO";
/* 13*/ DROP TABLE "MGROUPINFO";
/* 14*/ DROP TABLE "MGROUPHOSTINFO";
/* 15*/	DROP SEQUENCE "AGGREGATE_STATS_SEQ";
/* 16*/ DROP SEQUENCE "PORT_STATS_SEQ";
/* 17*/	DROP SEQUENCE "FLOW_STATS_SEQ";
/* 18*/	DROP SEQUENCE "EVENT_ID_SEQ";
/* 19*/	DROP SEQUENCE "MGROUP_ID_SEQ";
/* 20*/ DROP TABLE "LEGACYMACHOSTINFO";
/* 21*/ DROP TABLE "TCNSWITCHMASTERSHIPINFO";
/* 22*/ DROP TABLE "TCNCONTROLLERINFO";
/* 23*/ DROP TABLE "PMACENTRY";
/* 24*/ DROP TABLE "VPNTUNNELENTRY";
/* 25*/ DROP TABLE "VPNGATEWAYENTRY";
/* 26*/ DROP TABLE "VPNINSTANCEENTRY";





/* 26*/
CREATE TABLE "VPNINSTANCEENTRY" (
 "INSTANCE_ID" VARCHAR(50),
 "GATEWAY_ID" VARCHAR(32),
 "INSTANCE_ACCESS_NAME" VARCHAR(30) NOT NULL,
 "INSTANCE_ACCESS_IP" VARCHAR(25) NOT NULL,
 "INSTANCE_ACCESS_AUTH" VARCHAR(50) NOT NULL,
 "INSTANCE_ACCESS_PORT" NUMBER,
 "INSTANCE_IMAGE_ID" VARCHAR(50),
 "INSTANCE_PUBLIC_IP" VARCHAR(25)
);

/* 25*/
CREATE TABLE "VPNGATEWAYENTRY" (
 "GATEWAY_ID" VARCHAR(32) NOT NULL,
 "GATEWAY_NAME" VARCHAR(50) NOT NULL,
 "GATEWAY_DESC" VARCHAR(255) NOT NULL,
 "GATEWAY_PUBLIC_IP" VARCHAR(25) NOT NULL,
 "TARGET_NETWORK" VARCHAR(50),
 "FAILOVER" VARCHAR(25),
 "ASN" NUMBER(32),
 "LIFETIME" NUMBER,
 "STATUS" VARCHAR(10),
 "CREATED_TIME" TIMESTAMP,
 "UPDATED_TIME" TIMESTAMP,
 "INSTANCE_ID" VARCHAR(50),
 "CREATED_BY" VARCHAR(100),
 "UPDATED_BY" VARCHAR(100)
);

/* 24*/
CREATE TABLE "VPNTUNNELENTRY" (
 "TUNNEL_ID" VARCHAR(50) NOT NULL,
 "TUNNEL_NAME" VARCHAR(50) NOT NULL,
 "GATEWAY_ID" VARCHAR(32) NOT NULL,
 "LOCAL_IP" VARCHAR(25) NOT NULL,
 "REMOTE_IP" VARCHAR(25) NOT NULL,
 "LOCAL_SUBNET" VARCHAR(25) NOT NULL,
 "REMOTE_SUBNET" VARCHAR(25) NOT NULL,
 "PRE_SHARED_KEY" VARCHAR(64),
 "TUNNEL_STATUS" VARCHAR(10),
 "IKE" NUMBER(1) NOT NULL,
 "LIFETIME" NUMBER,
 "ROUTING_RULE" VARCHAR(100),
 "INSTANCE_ID" VARCHAR(50),
 "CREATED_TIME" TIMESTAMP,
 "UPDATED_TIME" TIMESTAMP,
 "CREATED_BY" VARCHAR(100),
 "UPDATED_BY" VARCHAR(100)
);


/* 23. PMAC ENTRY TABLE */
CREATE TABLE "PMACENTRY" (
    "ENTRY_ID" NUMBER NOT NULL,
    "PUBLIC_IP" VARCHAR(25) NOT NULL,
    "HOST_PMAC" VARCHAR(25) NOT NULL,
    "COOKIE" NUMBER(25) NOT NULL,
    "COOKIE_HEX" VARCHAR(100),
    "CREATED_TIME" TIMESTAMP
);


/* 22. TCNC CLUSTERING INFO */
CREATE TABLE "TCNCONTROLLERINFO" (
	"CONTROLLER_ID" NUMBER NOT NULL,
	"CONTROLLER_PID" NUMBER,
	"CONTROLLER_STATUS" VARCHAR(20),
	"CONTROLLER_NAME" VARCHAR(255),
	"CLUSTER_ID" NUMBER NOT NULL,
	"CLUSTER_STATUS" VARCHAR(20),
	"IP_ADDR" VARCHAR(30),
	"PORT" NUMBER,
	"START_TIME" TIMESTAMP,
	"UPDATED_TIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

ALTER TABLE "TCNCONTROLLERINFO" ADD
PRIMARY KEY (
	"CONTROLLER_ID"
);







/* 21. TCNC INFO */
CREATE TABLE "TCNSWITCHMASTERSHIPINFO" (
	"DPID" NUMBER(25) NOT NULL,
	"CONTROLLER_ID" NUMBER,
	"CLUSTER_ID" NUMBER,
	"MASTERSHIP_STATUS" VARCHAR(20),
	"UPDATED_TIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

ALTER TABLE "TCNSWITCHMASTERSHIPINFO" ADD
PRIMARY KEY (
	"DPID",
	"CONTROLLER_ID"
);

ALTER TABLE "TCNSWITCHMASTERSHIPINFO" ADD CONSTRAINT "FK_TCNSWITCHMASTERSHIPINFO_CONTROLLER_ID"
FOREIGN KEY (
	"CONTROLLER_ID"
) REFERENCES "TCNCONTROLLERINFO" (
	"CONTROLLER_ID"
);



/* 20. LEGACY MAC HOST INFO TABLE */
CREATE TABLE "LEGACYMACHOSTINFO" (
	"MAC_ID" NUMBER NOT NULL,
	"MAC_ADDR" VARCHAR(25) NOT NULL,
	"SW_DPID" NUMBER(25),
	"SW_PORT" NUMBER,
	"IPV4_ADDR" VARCHAR(25),
	"RULE_ID" NUMBER(25) NOT NULL,
	"VLANID" NUMBER,
	"CREATOR" VARCHAR(255),
	"UPDATED_TIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

ALTER TABLE "LEGACYMACHOSTINFO" ADD
PRIMARY KEY (
	"MAC_ID"
);







/* 19. MULTICAST GROUP ID SEQUENCE */
CREATE SEQUENCE "MGROUP_ID_SEQ"
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE 
CACHE 20
NOORDER ;







/* 18. EVENT ID SEQUENCE */
CREATE SEQUENCE "EVENT_ID_SEQ"
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE 
CACHE 20
NOORDER ;







/* 17. FLOW STATS ID SEQUENCE */
CREATE SEQUENCE "FLOW_STATS_SEQ"
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE 
CACHE 20
NOORDER ;







/* 16. PORT STATS ID SEQUENCE */
CREATE SEQUENCE "PORT_STATS_SEQ"
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE 
CACHE 20
NOORDER ;







/* 15. AGGREGATE STATS ID SEQUENCE */
CREATE SEQUENCE "AGGREGATE_STATS_SEQ"
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9999999999999999999999999999
NOCYCLE 
CACHE 20
NOORDER ;







/* 14. MULTICAST GROUP HOST INFO TABLE*/
CREATE TABLE "MGROUPHOSTINFO" (
	"HOST_ID" NUMBER(25) NOT NULL,
	"MGROUP_ID" NUMBER(25),
	"MAC_ADDR" VARCHAR(20),
	"SW_DPID" NUMBER(25),
	"SW_PORT" NUMBER,
	"CREATOR" VARCHAR(255),
	"UPDATED_TIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

--CREATE UNIQUE INDEX "UNIQUE_MGROUPHOSTINFO" ON "MGROUPHOSTINFO" (
--	"HOST_ID" ASC
--)
--LOGGING
--TABLESPACE "USR"
--PCTFREE 10
--INITRANS 2;

--ALTER TABLE "MGROUPHOSTINFO" ADD
--PRIMARY KEY (
--	"HOST_ID"
--);







/* 13. MULTICAST GROUP INFO TABLE */
CREATE TABLE "MGROUPINFO" (
	"MGROUP_ID" NUMBER NOT NULL,
	"MIP_ADDR" VARCHAR(20),
	"MMAC_ADDR" VARCHAR(20),
	"MGROUP_NAME" VARCHAR(1000),
	"VLAN_ID" NUMBER,
	"TENANT_ID" NUMBER(25),
	"OFGROUP_ID" NUMBER,
	"OFFLOW_ID" NUMBER(25),
	"CREATOR" VARCHAR(255),
	"UPDATED_TIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX "UNIQUE_MGROUPINFO" ON "MGROUPINFO" (
	"MGROUP_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

ALTER TABLE "MGROUPINFO" ADD
PRIMARY KEY (
	"MGROUP_ID"
);

ALTER TABLE "MGROUPINFO" ADD
UNIQUE (
	"MIP_ADDR",
	"VLAN_ID"
);




/* 12. EVENT INFO TABLE */
CREATE TABLE "EVENTINFO" (
	"EVENT_ID" NUMBER NOT NULL,
	"EVENT_NAME" VARCHAR(100),
	"EVENT_TYPE" VARCHAR(50),
	"EVENT_LEVEL" NUMBER,
	"SOURCE_TYPE" VARCHAR(50),
	"SOURCE_ID" VARCHAR(100),
	"IS_PUBLISHED" NUMBER(1),
	"UPDATED_TIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX "UNIQUE_EVENTINFO" ON "EVENTINFO" (
	"EVENT_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

ALTER TABLE "EVENTINFO" ADD
PRIMARY KEY (
	"EVENT_ID"
);







/* 11. ARP HOST INFO TABLE */
CREATE TABLE "ARPHOSTINFO" (
	"HOST_ID" NUMBER NOT NULL,
	"MAC_ADDR" VARCHAR(25),
	"IPV4_ADDR" VARCHAR(25),
	"SW_DPID" NUMBER(25),
	"SW_PORT" NUMBER,
	"VLAN_ID" NUMBER,
	"COMM_GROUP" VARCHAR(255),
	"START_TIME" TIMESTAMP,
	"UPDATED_TIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX "UNIQUE_ARPHOSTINFO" ON "ARPHOSTINFO" (
	"HOST_ID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

ALTER TABLE "ARPHOSTINFO" ADD
PRIMARY KEY (
	"HOST_ID"
);







/* 10. STATS INFO TABLE */
CREATE TABLE "STATSINFO" (
	"STATSID" NUMBER NOT NULL,
	"KEYNAME" VARCHAR(100) NOT NULL,
	"STATSTYPE" VARCHAR(100),
	"INTERVAL" NUMBER,
	"UPDATED_TIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX "UNIQUE_STATSINFO" ON "STATSINFO" (
	"STATSID" ASC

)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

ALTER TABLE "STATSINFO" ADD
PRIMARY KEY (
	"STATSID"
);







/* 9. GATEWAY TABLE */
CREATE TABLE "GATEWAYINFO" (
	"GATEWAY_ID" NUMBER(25) NOT NULL,
	"IPV4_ADDR" VARCHAR(100),
	"MAC_ADDR" VARCHAR(100),
	"SWITCH_DPID" NUMBER(25),
	"SWITCH_PORT" NUMBER(10),
	"CREATOR" VARCHAR(255),
	"START_TIME" TIMESTAMP,
	"UPDATED_TIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX "UNIQUE_GATEWAYINFO" ON "GATEWAYINFO" (
	"GATEWAY_ID" ASC
)
LOGGING
TABLESPACE USR
PCTFREE 10
INITRANS 2;

ALTER TABLE "GATEWAYINFO" ADD
PRIMARY KEY (
	"GATEWAY_ID"
);







/* 8. SWITCH TABLE */
CREATE TABLE "SWITCHENTRY" (
	"DPID" NUMBER(25),
	"DPID_HEX" VARCHAR(100),
	"PMAC_SW_ID" VARCHAR(10),
	"SWITCH_NAME" VARCHAR(500),
	"SWITCH_TYPE" VARCHAR(20),
	"STATUS" VARCHAR(10),
	"N_BUFFERS" NUMBER(10),
	"N_TABLES" NUMBER(10),
	"AUXILIARY_ID" NUMBER(10),
	"CAPABILITIES" NUMBER(10),
	"HW_DESC" VARCHAR(255),
	"MFR_DESC" VARCHAR(255),
	"SERIAL_NUM" VARCHAR(255),
	"SW_DESC" VARCHAR(255),
	"DP_DESC" VARCHAR(255),
	"CREATOR" VARCHAR(255),
	"START_TIME" TIMESTAMP,
	"UPDATED_TIME" TIMESTAMP
)
TABLESPACE "USR"
PCTFREE 10
INITRANS 2
STORAGE (
	MAXEXTENTS UNLIMITED
)
LOGGING
NOPARALLEL;

CREATE UNIQUE INDEX "UNIQUE_SWITCHENTRY" ON "SWITCHENTRY" (
	"DPID" ASC
)
LOGGING
TABLESPACE "USR"
PCTFREE 10
INITRANS 2;

ALTER TABLE "SWITCHENTRY" MODIFY 	"DPID" NOT NULL;
ALTER TABLE "SWITCHENTRY" ADD 
PRIMARY KEY (
	"DPID"
);

commit;
exit
