GRANT SELECT ON USERMGT.HISTORY TO AUTH;
GRANT SELECT ON USERMGT.PERMISSION TO AUTH;
GRANT SELECT ON USERMGT.PROJECT TO AUTH;
GRANT SELECT ON USERMGT.PROJECT_ROLE TO AUTH;
GRANT SELECT ON USERMGT.PROJECT_SERVICE TO AUTH;
GRANT SELECT ON USERMGT.PROJECT_USER_RELATION TO AUTH;
GRANT SELECT ON USERMGT.PROJECT_USER_ROLE_RELATION TO AUTH;
GRANT SELECT ON USERMGT.RESOURCE_QUOTA TO AUTH;
GRANT SELECT ON USERMGT.ROLE TO AUTH;
GRANT SELECT ON USERMGT.ROLES_RELATION TO AUTH;
GRANT SELECT ON USERMGT.ROLE_PERMISSION_RELATION TO AUTH;
GRANT SELECT ON USERMGT.SERVICE TO AUTH;
GRANT SELECT ON USERMGT.TENANT TO AUTH;
GRANT SELECT ON USERMGT.TENANT_ROLE TO AUTH;
GRANT SELECT ON USERMGT.TENANT_SERVICE TO AUTH;
GRANT SELECT ON USERMGT.TENANT_USER_RELATION TO AUTH;
GRANT SELECT ON USERMGT.TENANT_USER_ROLE_RELATION TO AUTH;
GRANT SELECT ON USERMGT.TEST TO AUTH;
GRANT SELECT ON USERMGT.USERS TO AUTH;

commit;
exit
