---

#### docker load / tag / push about IMAGE_NAME_1
- name: docker load {{ IMAGE_NAME_1 }}
  shell: "sudo docker load < {{ user_home.stdout }}/automation/image_import/{{ IMAGE_NAME_1 }}_{{ ssvr_tag }}.tar.gz"

- name: docker tag {{ IMAGE_NAME_1 }}
  shell: "sudo docker tag 172.31.2.1:5000/{{ IMAGE_NAME_1 }}:{{ ssvr_tag }} {{ image_registry }}:5000/{{ IMAGE_NAME_1 }}:{{ ssvr_tag }}"

- name: docker push {{ IMAGE_NAME_1 }}
  shell: "sudo docker push {{ image_registry }}:5000/{{ IMAGE_NAME_1 }}:{{ ssvr_tag }}"

#### docker load / tag / push about IMAGE_NAME_2
- name: docker load {{ IMAGE_NAME_2 }}
  shell: "sudo docker load < {{ user_home.stdout }}/automation/image_import/{{ IMAGE_NAME_2 }}_{{ tibero_tag }}.tar.gz"

- name: docker tag {{ IMAGE_NAME_2 }}
  shell: "sudo docker tag 172.31.2.1:5000/{{ IMAGE_NAME_2 }}:{{ tibero_tag }} {{ image_registry }}:5000/{{ IMAGE_NAME_2 }}:{{ tibero_tag }}"

- name: docker push {{ IMAGE_NAME_2 }}
  shell: "sudo docker push {{ image_registry }}:5000/{{ IMAGE_NAME_2 }}:{{ tibero_tag }}"


#### docker load / tag / push about IMAGE_NAME_3
- name: docker load {{ IMAGE_NAME_3 }}
  shell: "sudo docker load < {{ user_home.stdout }}/automation/image_import/{{ IMAGE_NAME_3 }}_{{ das_tag }}.tar.gz"

- name: docker tag {{ IMAGE_NAME_3 }}
  shell: "sudo docker tag 172.31.2.1:5000/{{ IMAGE_NAME_3 }}:{{ das_tag }} {{ image_registry }}:5000/{{ IMAGE_NAME_3 }}:{{ das_tag }}"

- name: docker push {{ IMAGE_NAME_3 }}
  shell: "sudo docker push {{ image_registry }}:5000/{{ IMAGE_NAME_3 }}:{{ das_tag }}"

#### docker load / tag / push about IMAGE_NAME_4
- name: docker load {{ IMAGE_NAME_4 }}
  shell: "sudo docker load < {{ user_home.stdout }}/automation/image_import/{{ IMAGE_NAME_4 }}_{{ ms_tag }}.tar.gz"

- name: docker tag {{ IMAGE_NAME_4 }}
  shell: "sudo docker tag 172.31.2.1:5000/{{ IMAGE_NAME_4 }}:{{ ms_tag }} {{ image_registry }}:5000/{{ IMAGE_NAME_4 }}:{{ ms_tag }}"

- name: docker push {{ IMAGE_NAME_4 }}
  shell: "sudo docker push {{ image_registry }}:5000/{{ IMAGE_NAME_4 }}:{{ ms_tag }}"

#### docker rmi IMAGE_NAME_1 & IMAGE_NAME_2 & IMAGE_NAME_3 & IMAGE_NAME_4
- name: docker rmi 172.31.2.1:5000/{{ IMAGE_NAME_1 }}
  shell: "sudo docker rmi 172.31.2.1:5000/{{ IMAGE_NAME_1 }}:{{ ssvr_tag }}"

- name: docker rmi {{ image_registry }}:5000/{{ IMAGE_NAME_1 }}
  shell: "sudo docker rmi {{ image_registry }}:5000/{{ IMAGE_NAME_1 }}:{{ ssvr_tag }}"

- name: docker rmi 172.31.2.1:500/{{ IMAGE_NAME_2 }}
  shell: "sudo docker rmi 172.31.2.1:5000/{{ IMAGE_NAME_2 }}:{{ tibero_tag }}"

- name: docker rmi {{ image_registry }}:5000/{{ IMAGE_NAME_2 }}
  shell: "sudo docker rmi {{ image_registry }}:5000/{{ IMAGE_NAME_2 }}:{{ tibero_tag }}"

- name: docker rmi 172.31.2.1:500/{{ IMAGE_NAME_3 }}
  shell: "sudo docker rmi 172.31.2.1:5000/{{ IMAGE_NAME_3 }}:{{ das_tag }}"

- name: docker rmi {{ image_registry }}:5000/{{ IMAGE_NAME_3 }}
  shell: "sudo docker rmi {{ image_registry }}:5000/{{ IMAGE_NAME_3 }}:{{ das_tag }}"

- name: docker rmi 172.31.2.1:500/{{ IMAGE_NAME_4 }}
  shell: "sudo docker rmi 172.31.2.1:5000/{{ IMAGE_NAME_4 }}:{{ ms_tag }}"

- name: docker rmi {{ image_registry }}:5000/{{ IMAGE_NAME_4 }}
  shell: "sudo docker rmi {{ image_registry }}:5000/{{ IMAGE_NAME_4 }}:{{ ms_tag }}"

