---
- name: Init ansible home
  hosts: '{{ hosts }}'

- name: Run tibero6 for TCNM
  hosts: '{{ hosts }}'
  environment:
    TB_HOME: '{{ tb_home }}'
    TB_SID: '{{ tb_sid }}'
    PATH: '{{ tb_home }}/bin:{{ tb_home }}/client/bin:{{ ansi_path }}'
    LD_LIBRARY_PATH: "{{ tb_home }}/lib:{{ tb_home }}/client/lib"
    TCNMTID: '{{ tcnm_db_user }}'
    TCNMTPW: '{{ tcnm_db_password }}'

  vars_files:
    - "../../vars/common_vars.yml"
    - "../../vars/db_config.yml"
  roles:
    - dbmanual_tcnm_run
