---
- name: Init ansible home
  hosts: '{{ hosts }}'
 
- name: Run Tibero6 with manual & execute csvmgr sql
  hosts: '{{ hosts }}'
  environment:
    TB_HOME: '{{ tb_home }}'
    TB_SID: '{{ tb_sid }}'
    PATH: "{{ tb_home }}/bin:{{ tb_home }}/client/bin:{{ ansi_path }}"
    LD_LIBRARY_PATH: "{{ tb_home }}/lib:{{ tb_home }}/client/lib"
    CSVMGR_META_DB_USER: '{{ CSVMGR_META_DB_USER }}'
    CSVMGR_META_DB_PWD: '{{ CSVMGR_META_DB_PWD }}'
  vars_files:
    - "../../vars/db_config.yml"

  roles:
    - dbmanual_csvmgr_run
