---
- name: Image update sql for initial(OFF to ON)
  hosts: '{{ hosts }}'
  environment:
    TB_HOME: '{{ tb_home }}'
    TB_SID: '{{ tb_sid }}'
    PATH: "{{ tb_home }}/bin:{{ tb_home }}/client/bin:{{ ansi_path }}"
    LD_LIBRARY_PATH: "{{ tb_home }}/lib:{{ tb_home }}/client/lib"
    TID: '{{ tid }}'
    TPW: '{{ tpw }}'

  vars_files:
    - "../../vars/common_vars.yml"
    - "../../vars/db_config.yml"

  roles:
    - image_update
