---
- name: Init ansible home
  hosts: '{{ hosts }}'

- name: Insert hostinfo, pportinfo, networkinfo, subnetinfo, vportinfo, publicipinfo sql
  hosts: '{{ hosts }}'
  environment:
    TB_HOME: '{{ tb_home }}'
    TB_SID: '{{ tb_sid }}'
    PATH: "{{ tb_home }}/bin:{{ tb_home }}/client/bin:{{ ansi_path }}"
    LD_LIBRARY_PATH: "{{ tb_home }}/lib:{{ tb_home }}/client/lib"
  vars_files:
    - "../../vars/common_vars.yml"
    - "../../vars/db_config.yml"

  roles:
    - infra_insert
