---
- name: Init ansible home
  hosts: '{{ hosts }}'

- name: RUN Cloud Master run
  hosts: '{{ hosts }}'
  vars_files:
    - "../../vars/common_vars.yml"
    - "../../vars/db_config.yml"
    - "../../vars/po7_vars.yml"
    - "../../vars/sysmanager_domain-config.yml"

  roles:
    - sysmanager_run
