---
- name: profile bash_profile
  stat:
    path="{{ user_home.stdout}}/.bash_profile"
  register: bprof
  become: true


- name: Adding the path in the Profile(.bash_profile) files
  lineinfile:
    dest: "{{ user_home.stdout }}/.bash_profile"
    line: "{{ item.line }}"
    #state: absent
    backup: yes
#    create: yes
    insertafter: "{{ item.after }}"
  with_items:
    - { line: "################add#####################
               \nexport PATH={{ jeus_home}}/bin:{{ jeus_home }}/lib/system:$PATH
               \nexport PROOBJECT_HOME={{ po_home }}
               \n################end#####################", after: "EOF" }
  when: bprof.stat.exists == True
  become: true

- name: profile profile
  stat:
    path="{{ user_home.stdout }}/.profile"
  register: prof
  become: true

- name: Adding the path in the Profile(.profile) files
  lineinfile:
    dest: "{{ user_home.stdout }}/.profile"
    line: "{{ item.line }}"
    #state: absent
    backup: yes
#    create: yes
    insertafter: "{{ item.after }}"
  with_items:
    - { line: "################add#####################
               \nexport PATH={{ jeus_home}}/bin:{{ jeus_home }}/lib/system:$PATH
               \nexport PROOBJECT_HOME={{ po_home }}
               \n################end#####################", after: "EOF" }
  when: prof.stat.exists == True
  become: true
