---

- name: make directory
  file: path={{ jeus_home }} state=directory

- name: make po_home directory
  file: path={{ po_home }} state=directory

- name: make tmp directory
  file: path=/{{ user_home }}/tmp/ state=directory
   

- name: copy license
  copy: src=../../../files/jeus-license/{{ item }}
        dest=/{{ user_home }}/tmp/
  with_items:
        - "license"

- name: gtar jeus
  unarchive:
    src=../../../files/binary/jeus8-b111.zip
    dest={{ jeus_home }}

- name: copy license
  command: "cp /{{ user_home }}/tmp/license {{ jeus_home }}/license"
  register: copy_lic_result


- name: copy tibero6 jdbc
  copy: src=../../../files/binary/tibero6-jdbc.jar dest={{ jeus_home }}/lib/datasource/
