---
- name: Init ansible home
  hosts: '{{ hosts }}'
 
- name: Install common jeus for po7
  hosts: '{{ hosts }}'
  vars_files:
    - "../../vars/common_vars.yml"
    - "../../vars/po7_vars.yml"
    - "../../vars/db_config.yml"
    - "../../vars/osarch_vars.yml"
    - "../../vars/iaas_domain-config.yml"
    - "../../vars/portal_server_domain-config.yml"
    - "../../vars/tcnm_domain-config.yml"
    - "../../vars/sysmanager_domain-config.yml"

  environment:
    PATH: "{{ jeus_home }}/bin:{{ jeus_home }}/lib:{{ ansi_path }}"
    PROOBJECT_HOME: "{{ po_home }}"

  roles:
    - common_install_jeus_forpo
