---
- name: Install portal master using Docker
  hosts: '{{ hosts }}'
  remote_user: '{{ user }}'
  vars_files:
    - "../../vars/po7_vars.yml"
    - "../../vars/portal_domain-config.yml"
  roles:
    - docker_portal_master_install 
