---
- name: Setting host network & apply
  hosts: '{{ hosts }}'
  vars_files:
    - "../../vars/common_vars.yml"
    - "../../vars/bridge_setting_lite.yml"
  environment:
    SETTING_NETMASK: '{{ SETTING_NETMASK }}'
    SETTING_GATEWAY: '{{ SETTING_GATEWAY }}'
    SETTING_GATEWAY_NET: '{{ SETTING_GATEWAY_NET }}'
    SETTING_INTERFACE: '{{ SETTING_INTERFACE }}'
  roles:
    - network_setting_apply
