---

- name: Setting sysmanager agent
  hosts: '{{ hosts }}'
  environment:
    master_ip: '{{ master_ip }}'
    TMAX_SYSMANAGER_PORT: '{{ TMAX_SYSMANAGER_PORT }}'
    TMAX_SYSMANAGER_IP: '{{ TMAX_SYSMANAGER_IP }}'
    TMAX_SYSMANAGER_AGENT_PORT: '{{ TMAX_SYSMANAGER_AGENT_PORT }}'
    TMAX_SYSMANAGER_AGENT_ANYMINER_PORT: '{{ TMAX_SYSMANAGER_AGENT_ANYMINER_PORT }}'
    TMAX_SYSMANAGER_AGENT_ANYMINER_IP: '{{ TMAX_SYSMANAGER_AGENT_ANYMINER_IP }}'
    TMAX_SYSMANAGER_AGENT_CONTAINER_RW_LAYER_DIRECTORY: '{{ TMAX_SYSMANAGER_AGENT_CONTAINER_RW_LAYER_DIRECTORY }}'
    TMAX_SYSMANAGER_AGENT_HOST_INTERFACE: '{{ TMAX_SYSMANAGER_AGENT_HOST_INTERFACE }}'
    TMAX_SYSMANAGER_AGENT_REPORT_LOCATION: '{{ TMAX_SYSMANAGER_AGENT_REPORT_LOCATION }}'
    TMAX_SYSMANAGER_AGENT_QEMU_IMAGE_FILE_DIRECTORY: '{{ TMAX_SYSMANAGER_AGENT_QEMU_IMAGE_FILE_DIRECTORY }}'
  vars_files:
    - "../../vars/common_vars.yml"

  roles:
    - sysmanager_agent
