---
- name: Init ansible home
  hosts: '{{ hosts }}'

- name: Install Sysmanager po7 manaually
  hosts: '{{ hosts }}'
  vars_files:
    - "../../vars/common_vars.yml"
    - "../../vars/tcnm_po7_vars.yml"
    - "../../vars/tcnm_domain-config.yml"
    - "../../vars/osarch_vars.yml"
    - "../../vars/db_config.yml"

  environment:
    PATH: "{{ jeus_home }}/bin:{{ jeus_home }}/lib:{{ ansi_path }}"
    PROOBJECT_HOME: "{{ po_home }}"

  roles:
    - tcnm_install
