---
- name: Find my home
  shell: "grep '{{ ansible_user }}:' /etc/passwd | awk -F: '{ print $6 }'"
  register: user_home

- name: Make compute directory
  file: path={{ user_home.stdout }}/automation/{{ item }} state=directory
  with_items:
    - im_scp

- name: Copy lxc install shell
  copy: src=../../../files/image_scp_install.sh dest={{ user_home.stdout }}/automation/im_scp/ mode=0755
  when: ansible_distribution == "Ubuntu" and aptInstall == "yes"

- name: install lxc
  shell: "nohup {{ user_home.stdout }}/automation/im_scp/image_scp_install.sh"
  when: ansible_distribution == "Ubuntu" and aptInstall == "yes"

- name: copy tca-image-scp
  copy: src=../../../files/tca-image-scp dest=/etc/init.d/tca-image-scp

- name: Setting tca-image-scp file
  replace:
    dest: "/etc/init.d/tca-image-scp"
    regexp: "{{ item.exp }}"
    replace: "{{ item.rep }}"
  with_items:
    - { exp: '@@user_home@@', rep: '{{ user_home.stdout }}' }

- name: Copy setting shell
  copy: src=../../../files/image_scp_setting.sh dest={{ user_home.stdout }}/automation/im_scp/image_scp_setting.sh mode=0755

- name: Setting shell
  shell: "sh {{ user_home.stdout }}/automation/im_scp/image_scp_setting.sh"
